packages-web/star-rating/package.json, packages-web/star-rating/src/components/StarRating.ts, packages-web/star-rating/src/components/__tests__/StarRating.spec.ts, packages-web/star-rating/tests/e2e/StarRating.spec.ts, packages-web/star-rating/tests/e2e/pages/home.page.ts
This MR fixes a problem where star rating stars from 1 instead of 0, resulting the widget to always render 1 less stars.
Bonus:
Fix package.json tests not migrated properly
Fix e2e url
=> Fix/web/star rating/renders 1 star less

packages-native/safe-area-view/package.json, packages-native/safe-area-view/src/SafeAreaView.tsx, packages-native/safe-area-view/src/__tests__/__snapshots__/SafeAreaView.spec.tsx.snap, packages-native/safe-area-view/src/package.xml
The safe area view widget won't intercept touch events, so that it allows for interaction with widgets behind the safe area view widget.
=> Feat: native safe area view widget - prevent touch event interception

detox/specs/colorPicker.spec.ts, packages-native/app-events/src/AppEvents.tsx, packages-native/app-events/src/__tests__/AppEvents.spec.tsx
- We fixed an error where on certain conditions onLoad event wouldn't trigger. Fixes: https://mendixsupport.zendesk.com/agent/tickets/96361
=> fix(app-events): trigger onload in correct state to fix canexecute=false

packages-common/nanoflow-commons/package.json, packages-common/piw-utils/package.json, packages-hybrid/hybrid-mobile-actions/package.json, packages-native/actions/package.json, packages-native/util-widgets/package.json, packages-web/actions/package.json
Dear team,
The `rm` command is an Unix command that is not compatible with Windows.
Using `rimraf` will make build and install run cross OS 
Travis CI is running windows build. Though the OS includes the GitBash shell. So *NIX commands will run.... but other widget devs might not run it from the same shell.
Cheers, Andries
=> fix: prebuild windows compatible

packages-native/actions/src/camera/TakePicture.ts
Fixing security issue found by @mgroeneweg. 
Case: When we take a picture the same file was being saved in the Library for Android and being kept inside App folder for iOS.
Tested using previous version of SP 8.8 and current versions.
@mgroeneweg I would like to also request your approval for this PR, also attached the MPK to the ticket.
=> [WT-2521] TakePicture JavaScript action stores picture in temporary folder

packages-web/calendar/package.json, packages-web/calendar/src/components/Calendar.ts, packages-web/calendar/src/components/CalendarContainer.ts, packages-web/calendar/src/package.xml
- When start date attribute value changes, the current date of BigCalendar is updated. Default date only initializes current date.
- Improve getStartPosition implementation
=> fix(calendar): start postion updating

packages-native/web-view/package.json, packages-native/web-view/src/WebView.tsx, packages-native/web-view/src/WebView.xml, packages-native/web-view/src/__tests__/WebView.spec.tsx, packages-native/web-view/src/package.xml, packages-native/web-view/typings/WebViewProps.d.ts
Web view widget: added new property: "Open links externally".
If true, links embedded in source document will be opened in external browser instead of inside this widget.
=> Web view: new prop: Open links externally

packages-common/pluggable-widgets-tools/scripts/gulp.js
I am using the `@mendix/widget` generator to generate both Pluggable as well as Custom React widgets. For the latter, I have been using the `pluggable-widget-tools` as well, which worked fine in 8.6.0.
In the newer versions of the tools, the typings generator that generates typings from the XML, is always enabled (even if I change my `build` command in `package.json` to `pluggable-widgets-tools build:js`).
As we're already loading the `.env` file from a widget project folder (so we can set the proper path to the Mendix project), I suggest adding an extra option there:
`MX_SKIP_TYPEGENERATOR`
If you add this to the `.env` file, it will skip the typings generator and the pluggable widgets tools will work for custom React widgets as well
=> Add option to skip typings generator

packages/customWidgets/slider-web/tests/e2e/specs/Slider.spec.ts
After run locally multiple times the slider mf/nf test starts failing here:
`[firefox 79.0 mac #0-0] 1) Slider triggers a microflow after slide
[firefox 79.0 mac #0-0] Expected '' to contain '0'.
[firefox 79.0 mac #0-0] Error: Expected '' to contain '0'.
[firefox 79.0 mac #0-0]     at <Jasmine>
[firefox 79.0 mac #0-0]     at <Jasmine>
[firefox 79.0 mac #0-0]     at UserContext.<anonymous> (/Users/leonardo.de.souza/Documents/Projects/widgets-resources/packages/customWidgets/slider-web/tests/e2e/specs/Slider.spec.ts:66:47)`
=> test(slider-web): fix mf/nf test spec

packages/tools/generator-widget/generators/app/lib/prompttexts.js, packages/tools/generator-widget/package.json, packages/tools/pluggable-widgets-tools/package.json, packages/tools/pluggable-widgets-tools/scripts/gulp.js
- Changes default MX test project folder to `./tests/TestProject` in PIW generator.
- Fixes webpack not bundling multiple times in Gulp watch mode.
- Fixes bug where native widgets would be copied in the web widgets deployment folder.
- Improves Gulp messaging.
Fixes #218
=> Fix PIW tools script bugs & improve PIW generator default MX project path

packages/pluggableWidgets/bottom-sheet-native/package.json, packages/pluggableWidgets/bottom-sheet-native/src/BottomSheet.tsx, packages/pluggableWidgets/bottom-sheet-native/src/components/ExpandingDrawer.tsx, packages/pluggableWidgets/bottom-sheet-native/src/package.xml
In this PR we are implementing the execution of actions for onOpen and onClose in expanding bottomsheets.
Details:
- The events were attached to:
- OnClose -> onCloseEnd because this action should only be triggered if the bottom sheet is already closed.
- OnOpen -> onOpenStart because if attached to onOpenEnd it will be triggered twice for fullscreen bottom sheet (2 stages) and when starting to open there is no way to stop.
=> fix(bottom-sheet-native): fixing onOpen and onClose events

packages/tools/generator-widget/generators/app/index.js, packages/tools/generator-widget/generators/app/templates/commons/.gitignore, packages/tools/generator-widget/generators/app/templates/commons/.prettierignore, packages/tools/generator-widget/generators/app/templates/pluggable/web/emptyTemplateTs/src/components/__tests__/HelloWorldSample.spec.tsx.ejs, packages/tools/generator-widget/generators/app/templates/pluggable/web/fullTemplateTs/src/components/__tests__/BadgeSample.spec.tsx.ejs, packages/tools/pluggable-widgets-tools/bin/mx-scripts.js
- Fix prettier command to also prettify `tests` folder.
- Add `.prettierignore` to prevent prettifying MX (test) project. Eslint only touches source, so there's no need to ignore anything there.
- Add `.gitignore` to prevent PIW-devs from committing a MX (test) project.
- Run `npm run lint:fix` after scaffolding the project.
- Fix lint warnings in unit test spec files of web templates.
=> Fix linting in PIW tooling

packages/jsActions/native-mobile-resources/README.md
So that the documentation is easily available and only needs to be maintained in one place, the README for this component should feature a link to the proper component doc published in the App Store Guide. This is also the content that should appear on the **Documentation** tab in the App Store for the component upon the next and all future releases.
Please update the App Store Guide as you update the component.
You can contact me with any questions.
=> Add link to documentation

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx
In this PR we fixed 2 issues identified by Danny:
- Sorting is just working as string, so number and dates act strange
- While applying filters the pagination always keep the original number of rows as total.
=> [WT-2714] fix of sorting based on attribute type and pagination while filter is applied

packages/tools/pluggable-widgets-tools/bin/mx-scripts.js, packages/tools/pluggable-widgets-tools/package.json
The gulp command currently fails if you have spaces in your project path. This commit adds quotes around the two paths in the gulp command.
=> fix(pwt): spaces in project path

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/Pagination.tsx, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/ColumnSelector.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Header.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Header.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/ui/Datagrid.scss, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/pluggableWidgets/datagrid-web/typings/react-table-config.d.ts
- Implementing state storing for initial state in sorting, filtering, hiding, paging and reordering
- Implementing filter method (startsWith, endsWith and contains)
- Fixing CSS when columns contains big untruncated texts
- Making it ready to receive custom configuration object from the users/SP
- Renaming properties not complying with Mendix standards
- Add a column with dynamic custom with a Button that open a popup page receiving a context parameter, then add a datagrid in the new page with editable fields. When you save the Data it should keep the current state of the datagrid. If tested with previous versions it will reset the DG as soon as you save or cancel in the popup. 
- Use variations: Microflow & nanoflow action buttons that change a parameter of a received …
=> feat(datagrid-web): implementing state for sorting, filtering, hiding, paging and reordering

packages/theming/atlas/src/native/ts/core/widgets/dropdown.ts
The native DropDown (uniform) component defaulted to a white background colour. This change introduces an explit backgroundColor css property.
[Atlas 2 PR](https://github.com/mendix/Atlas-UI-Framework/pull/96)
=> [WT-2771] Correct native dropdown menu background color

packages/jsActions/native-mobile-resources/src/deeplink/ParseUrlToObject.ts
The call to UrlParse was missing a second parameter. Without it, the query string does not get parsed.
Documentation here: https://www.npmjs.com/package/url-parse
=> fix(native-mobile-resources): ParseUrlToObject

packages/theming/atlas/src/native/ts/core/widgets/dropdown.ts
In porting changes from Atlas 2 -> 3, some CSS properties were included in the incorrect object/place, breaking menu items' alignment.
This change set addresses this and corrects alignment as per designs.
=> Correct dropdown menu item value alignment

packages/theming/atlas/src/native/ts/app/custom-variables.ts, packages/theming/atlas/src/native/ts/core/variables.ts, packages/theming/atlas/src/native/ts/core/widgets/dropdown.ts, packages/theming/atlas/src/native/ts/types/variables.d.ts, packages/theming/atlas/src/native/ts/types/widgets.d.ts
Native Dropdown (Uniform) menu items on iOS in dark mode had two issues:
- if you pressed the selected item it would flash white, essentially due to Atlas missing an `underlayColor` property and the 3rd-party component previously defaulting this to white-ish. 
- the `underlayColor` would "bleed" out of the edges, essentially due to how the previously used 3rd-party component would include a `View` component as a child to the `TouchableHighlight`. 
This has been corrected with this changeset, by correcting styling and introducing an implementation of MenuItem.
- Android and iOS (light + dark) native Dropdown styling (Atlas 3)
- No regression in native ReferenceSelector styling (which used DropdownUniform)
NN
=> Native dropdown menu items styling

packages/pluggableWidgets/notifications-native/package.json, packages/pluggableWidgets/notifications-native/src/Notifications.tsx, packages/pluggableWidgets/notifications-native/src/Notifications.xml, packages/pluggableWidgets/notifications-native/typings/NotificationsProps.d.ts
Added attribute properties for the following attributes of a notification:
- title
- subtitle
- body
- action
The use case is the following:
- app receives notification while it is active
- on iOS, the standard behavior is that notifications are silently sent to the handler
- we want to display some notification details to the user
- in the handler nanoflow, we had none of the notification details (only had access to a GUID)
This PR adds access to the core data of a notification so we can show an appropriate message or a local notification
=> feat(notifications-native): new optional attribute properties

packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/utils/__tests__/settings.spec.ts, packages/pluggableWidgets/datagrid-web/src/utils/settings.ts, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
**In this PR I am:**
- Introducing custom user settings attribute
**What does it mean?**
It means that from now one you can save your current DataGrid configurations like: applied filters, sort, columns order, hidden columns and column width (if you resized) in an attribute that will be loaded once the DG is ready to render.
**IMPORTANT**
The attribute should be of type unlimited string, otherwise it will not be able to perform all the settings if you have a good amount of columns.
**How to test**
To be able to test your need to use RC or Master, because of WTF-551
=> [WT-2723] Data grid - User custom configuration

packages/pluggableWidgets/notifications-native/package.json, packages/pluggableWidgets/notifications-native/src/Notifications.tsx, packages/pluggableWidgets/notifications-native/src/package.xml
Why?
This fix an issue where an attribute was still loading the was receiving notifications at the same time, which could cause the attribute to not be set and you loose the notification.
How?
- I moved the code to functional component to keep the consistency of other widgets and added extra checks if an attribute is set and the status is not available then it waits to subscribe for notifications only when the attributes are ready to be used.
How to test?
You need to set a project in firebase, configure a project using Native Builder UI an onOpen set a nanoflow that takes time or even nanoflow with subnanoflows.
=> fix(notifications-native): fixing attributes in loading state

packages/theming/atlas/src/native/ts/core/widgets/dropdown.ts
The Reference Selector styles are spread out from Dropdown's, meaning this change will cover the icon color for Reference Selector.
=> Add missing colour styling property for Dropdown Uniform icon

packages/pluggableWidgets/line-chart-native/src/LineChart.tsx, packages/pluggableWidgets/line-chart-native/src/components/LineChart.tsx, packages/pluggableWidgets/line-chart-native/src/ui/Styles.ts
The axis label functionality of Victory JS is to limited with regard to positioning and flexibel grid resizing.
- Separate labels as RN `Text` components
- Restructure RN `View` components to facilitate flexible label positioning
- Add style property `positionRelativeToGrid` to `xAxisLabel` and `yAxisLabel` (both `TextStyle`). `xAxisLabel` has positions `bottom` (default) and `right`, `yAxisLabel` has `top` (default) and `left`.
- Add warning for invalid `positionRelativeToGrid` label style property and `display` marker style property.
Bonus:
- Render markerts by default on top
- Adjust the styling related to labels to see it's capabilities.
=> [N] Line chart - Add separate axis labels

packages/pluggableWidgets/datagrid-web/src/utils/__tests__/settings.spec.ts, packages/pluggableWidgets/datagrid-web/src/utils/settings.ts
Why?
Currently we check if is the first load then load the settings, but in some cases users needs to change dynamically the settings.
=> Fixing DG custom settings

packages/tools/pluggable-widgets-tools/configs/tsconfig.base.json, packages/tools/pluggable-widgets-tools/configs/webpack.config.common.js, packages/tools/pluggable-widgets-tools/configs/webpack.config.dev.js, packages/tools/pluggable-widgets-tools/configs/webpack.config.prod.js, packages/tools/pluggable-widgets-tools/configs/webpack.native.config.js
**In this PR I am:**
- Fixing implicit definition of CommonJS for editorPreview and editorConfig files (Which doesnt need anymore due to exnext module
- Fixing CSS loaders for editorPreview (should be bundled as string)
=> Fixing Webpack Configurations

.github/workflows/ScriptTests.yml, .github/workflows/UnitTests.yml, .github/workflows/WebAutomatedTests.yml
Adding extra rule to only fetch target branch if is a PR (push should always execute full builds)
=> fix: fixing rule to fetch master branch only if PR triggered it

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx
In this PR we are fixing the preview (Design mode) when a Data grid is dropped without any data.
=> [WT-2992] Data grid - Fix preview when no data is set

packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/ui/Datagrid.scss, packages/pluggableWidgets/datagrid-web/src/utils/__tests__/settings.spec.ts, packages/pluggableWidgets/datagrid-web/src/utils/settings.ts, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
To persist new configuration changes of users, mx devs should be able to trigger an action after these changes occur.
- An `On change` action property has been added to the `Configuration` property group to trigger an action after the settings attribute value has been updated.
- Include some background style improvements.
Check whether action is triggered correctly and if style changes don't break the widget.
=> [W] Data grid - Add on configuration change property

packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts
In story PAG-1438 we removed the borders to be rendered by default. This PR adds rounded borders to the dg filters. Also includes a little fix when no columns exist but columnsFilterable == true.
I also removed the border around the data grid because the double border looked sorta weird. If you want it back, be my guest.
Can wait for Diego to come back from his holiday.
Here is a little screenshot (with parallels and weird dpi) of what it will look like
=> feat(datagrid-web): adopt datagrid configs to new logic [PAG-1438]

.gitmodules, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/tests/e2e/objects/datagrid.widget.ts, packages/pluggableWidgets/datagrid-number-filter-web/tests/e2e/specs/DataGridNumberFilter.spec.ts, packages/pluggableWidgets/datagrid-number-filter-web/tests/e2e/tsconfig.json
Why?
Adding e2e tests to cover datagrid-text-filter-web widget.
=> test(datagrid-number-filter-web): add e2e test

packages/customWidgets/calendar-web/package.json, packages/customWidgets/calendar-web/src/Calendar.xml, packages/customWidgets/calendar-web/src/components/CalendarContainer.ts, packages/customWidgets/calendar-web/src/package.xml, packages/customWidgets/calendar-web/src/utils/namespaces.ts, packages/customWidgets/calendar-web/src/utils/validation.ts
There are widget config properties present to alter the date formatting of dates inside the header of the day, week, work week, month and agenda view. This didn't work, because there was no logic passed to `react-big-calendar`.
- Pass custom header formatters for day, week, month, work week and agenda view.
- Remove default value for `headerFormat` widget config property to allow for default `react-big-calendar` notations.
- Improve `headerFormat` property description.
- Only validate `headerFormat` value when it's not an empty.
- Check the header of the views: day, week, work week, month and agenda view. 
- Check the default header when no value is configured for the `headerFormat` (Header day format) widget config property.
- Check custom formats and that they are only applied to the …
=> [WT-3116] Fix header day formatting for calendar-web widget

packages/pluggableWidgets/video-player-web/src/components/SizeContainer.tsx, packages/tools/pluggable-widgets-tools/jest.config.js, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/index.spec.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/containment.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/file.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/containment.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/datasource.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/file.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/icon.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/index.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-action.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-files.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-image.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/generate.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/generateClientTypes.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/helpers.ts, packages/tools/pluggable-widgets-tools/tests/commands.js
- Add `id` prop for web widgets with system property `Label`
- Bonus fix: properly declare `tabIndex` prop as optional
=> [WT-3097] PIW tools - Generator doesn't include id property in typings (Mx 9)

packages/customWidgets/calendar-web/src/components/CalendarContainer.ts
This PR relates to Support Ticket #115446 and 
#115684
When the widget is loaded subscriptions are created for each object in the calendar. On unmount they are unsubscribed. This works fine in most cases. However when the widget is destroyed before the data is retrieved a problem arises. 
When the data comes back after the unmount event, it will never be unsubscribed. When the widget is opened again there will be duplicate subscriptions cause the widget to end up in a refresh loop. (Overloading the Mendix server)
To prevent this, the widget should have an internal state and discard the fetched objects when they are received after the widget is destroyed.
=> fix(calendar-web): cancel loading after destroy

packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
**What i am doing in this PR?**
In this PR I am adding a extra property for columns to allow TextTemplate to be added ootb, I am also reordering properties to make usability better. In addition we also renamed sortable, resizable, draggable and hideble to can sort, can resize, can reorder and can hide to sounds better.
**Why?**
Because sometimes users need fast actions, this will prevent them to add manually a text template and them select the attributes that should be part of that. With the reordering it makes more comfortable tabs for Studio and makes things more clear for Studio Pro.
- Combine with filters, disable filterability and sortability.
Rules:
- If Sorting or Filtering is enable then the columns will always require a attribute (to be able to filter and sort), …
=> feat(datagrid-web): add text template and reorder properties

packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx
**What I am doing in this PR?**
In this PR I am fixing an issue when the row contain a click event and also a filter widget is being applied.
**Why?**
The DG was passing the wrong value object to the action (preserving the original state), in this case the filtered object was not being passed to the action.
Place a DG containing a row click event and drop a filter widget. After filter it should pass the correct object to the action.
=> Data Grid - Fix wrong context when filter is applied

packages/customWidgets/calendar-web/package.json, packages/customWidgets/carousel-web/package.json, packages/customWidgets/color-picker-web/package.json, packages/customWidgets/image-viewer-web/package.json, packages/customWidgets/progress-bar-web/package.json, packages/customWidgets/progress-circle-web/package.json, packages/customWidgets/range-slider-web/package.json, packages/customWidgets/rich-text-web/package.json, packages/customWidgets/signature-web/package.json, packages/customWidgets/slider-web/package.json, packages/customWidgets/star-rating-web/package.json, packages/customWidgets/switch-web/package.json, packages/pluggableWidgets/badge-button-web/package.json, packages/pluggableWidgets/badge-web/package.json, packages/pluggableWidgets/badge-web/typings/BadgeProps.d.ts, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/fieldset-web/package.json, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/timeline-web/package.json, packages/pluggableWidgets/video-player-web/package.json, packages/tools/pluggable-widgets-tools/scripts/e2e.js, scripts/test/updateAtlas.js
To iteratively convert web test projects to mx 9 and atlas 3, we need to be able to run e2e test on both mx 8 and 9 version as well as Atlas 2 (released) and Atlas 3 changes. Also, we can use this in the future to test web widgets on multiple mx platforms.
- Add an option `--mx-version` to which a version argument, like `8` or `9`, can be passed.
- Add an option `--latest-atlas` to test with Atlas inside mono repo. Without the option, latest released Atlas from Atlas-UI-Framework is used.
- Update all `test:e2e` scripts for web widgets to use mx major version 8.
- All e2e tests should pass.
=> Make e2e test execution configurable

packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/ui/Datagrid.scss, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
**What I am doing in this PR?**
I am fixing the alignments in the empty placeholder dropzone (container) by adding a div filling the whole space. I am also adding the capability to use headers without a caption.
**Why?**
Because sometimes users dont need to define a header caption, also the alignments in the empty placeholder were wrong due to flex.
Drag in things in the empty placeholder without add an extra container and set the alignment of its elements to center and check if it behaves as expected. To test the empty caption.. well, just remove the caption :P
=> Data grid - Empty header & placeholder fix

packages/pluggableWidgets/maps-web/package.json
There's a bug when running e2e tests for maps-web using mx-8.18. However, now is possible to define which version to use when running the e2e tests(https://github.com/mendix/widgets-resources/pull/439). I did that, changing this specs for maps-web to run using mx-9 image.
=> maps-web: fix error using mx version 9

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/tools/piw-utils/src/utils/PageEditorUtils.ts
**In this PR I am:**
Adding a method that converts property groups into tabs to be used in Studio.
**Why?**
Because in Studio groups are not being rendered as fieldsets.
Run a project in the cloud and test in Studio (Applies only to 8.18.1), in SP it should remains the same.
=> [WC-140] Transform groups into tabs for Studio - Apply to Data Grid

packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts
**Why?**
Users where having problem to find out where the properties of the data grid are reachable. While PE is creating a header component, this will be used. The new one will also show the icon and the source.
**Bonus**
- Adding borders to the filters due to 9.0.3 removed the default border.
=> [WC-148] Add header to Data grid preview

packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx
**Why?**
Practice shows that pluggable widgets rarely use `ListValue.totalCount`, but currently its value is requested from the runtime for all data sources. This is unfortunate, since computing `totalCount` can be expensive.
What I did in this PR?
- Added a backwards compatible call to `requestTotalCount`
How to test?
- To force the datasource to request totalCount the DG should be configured without Sorting or Filtering.
=> feat(datagrid-web): add requestTotalCount

packages/pluggableWidgets/timeline-web/package.json, packages/pluggableWidgets/timeline-web/src/package.xml
The structure preview changes are not compatible with MX8, therefore this widget is now v2.0.0.
=> Prepare for timeline web 2.0.0 release

packages/pluggableWidgets/video-player-native/src/VideoPlayer.tsx, packages/pluggableWidgets/video-player-native/src/VideoPlayer.xml, packages/pluggableWidgets/video-player-native/src/__tests__/VideoPlayer.spec.tsx, packages/pluggableWidgets/video-player-native/src/__tests__/__snapshots__/VideoPlayer.spec.tsx.snap, packages/pluggableWidgets/video-player-native/src/ui/Styles.ts
`property => Aspect ratio boolean property`
Property was not making any difference in the video presentation. Not sure how many people were switching this property off but it wasn't working correctly.
- Depending on the property, we now set the resize mode of the video (contain, stretch). This will actually allow video to resize as expected. 
- Since we are not setting `aspectRatio` style property when the property set to false, we extended the helper text so people should add "height" and "width" to have the best result.
- Before the surrounding container was not respecting the size of the video, now it does.
Converted to functional component
=> [NC-155] VIdeo Player - Fix aspect ratio

packages/theming/atlas/src/theme/web/login-with-sso.html, packages/theming/atlas/src/theme/web/login.html
The login pages have a header "Sign in" which now has an ID that the login.js script can target for translations.
=> [Atlas] Allow targeting login header

packages/theming/atlas/scripts/build.js
Remove quotes around arguments, so that Windows machines execute the commands correctly as well.
=> Fix Atlas build script for Windows

packages/theming/atlas/src/theme/web/custom-variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/_variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_groupbox.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_labels.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_typography.scss, packages/theming/atlas/src/themesource/atlas_core/web/design-properties.json
The info and inverse brand styles are not encourgaed to be used anymore with Atlas 3.
- The info and inverse brand styles have been removed from design properties. 
- The info and inverse brand style Atlas variables have been moved at the bottom of the variable files under the heading "Legacy".
X
=> [WC-98] Update atlas style variations

packages/theming/atlas/scripts/build.js
Due to the missing quotes in the build script, output for web folders were missing files. Tested on Unix and Windows.
=> Fix Atlas build script output

packages/pluggableWidgets/progress-bar-web/src/components/ProgressBar.tsx, packages/pluggableWidgets/progress-bar-web/src/components/__tests__/__snapshots__/ProgressBar.spec.tsx.snap, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_progressbar.scss, packages/theming/atlas/src/themesource/atlas_core/web/design-properties.json
Follow up to #455.
There were a few things that had to be updated based on testing feedback and then design feedback that resulted out of it.
Based on input from @cjfhodges:
- We won't provide the user options for the background color anymore, rather we just stick to `#f8f8f8`
- Narrow the bar color options down to Primary, Success, Warning, and Danger. Default is Primary
- Remove option for an animated progress bar and only allow striped or not-striped -> instead of Dropdown we use a toggle design property.
This also holds for progress circle, so I will update #495 accordingly.
=> [WC-109] Update progress bar according to design feedback

.prettierrc, package.json, prettier.config.js
The goal here is to format consistenty in scripts, on-commit hook and on-save actions.
- temporarily introduce a `.rc` file matching `.js` configuration as pretty-quick doesn't read in `.js` files. I don't see this as an issue as our config doesn't change often. Until pretty-quick reads `.js` we need to maintain both files.
- remove filepath configuration prop as [this is not recommend in configuration](https://prettier.io/docs/en/options.html#file-path)
- update patterns to remove relative start, and include scripts. Apply this across the board.
I think it is a good idea to make a PR to pretty-quick to include reading `.js` files as we depend on this for dynamic base extension.
Webstorm glob suggestion for prettier plugin: `{**/*,*}.{js,jsx,ts,tsx,spec.ts,spec.tsx,css,scss}`
=> Correct pretty-quick config

packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_badgebutton.scss, packages/theming/atlas/src/themesource/atlas_core/web/design-properties.json
Added design properties to badge button to align with that of button.
Added styles to Atlas_Core (we might want to consider adding badge to button mixin in Atlas_Core)
Added the "brand primary" option to design property option, as we need an intuitive way to reset button style back to button primary as set to blank is not intuitive.
=> Badge button design properties

packages/theming/atlas/src/theme/web/custom-variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/_variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/main.scss
Move the import of custom fonts to `main.scss` to avoid duplicate imports in CSS output.
Both `variables.scss` and `custom-variables.scss` were importing the custom font, which resulted in potentially duplicate import statements in CSS (if the condition was met).
This depends on page editor team fixing an issue in Studio Pro around overriding SCSS's `url` functionality: https://mendix.atlassian.net/browse/PAG-1498
- set a custom font in `custom-variables` and ensure MX app renders this user-defined custom font. There should only be one import statement in CSS.
- remove the custom font from `custom-variables` and ensure MX app renders atlas-defined custom font. There should only be one import statement in CSS.
=> [WC-43] Correct atlas font import

.github/workflows/ScriptTests.yml, .github/workflows/UnitTests.yml, .github/workflows/WebAutomatedTests.yml
This GH Action changes the way we obtain changed files, it also already filter for global files and we can skip fetch master if some global file was changed because lerna does not require master in this case.
This GH Action uses internal API from the toolkit to discover the files, which I hope will not fail every time someone pushes something to master.
Reference: https://github.com/softprops/diffset/blob/master/src/diff.ts
=> feat: change gh action for changed files

packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/containment.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/datasource.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
Added a new property for the Widgets Type (dropzones)
- caption
- this will override the default caption that is shown when the dropzone is empty
=> [PAG-1449] Add prop for the widgets type

package-lock.json, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/maps-web/src/Maps.editorPreview.tsx, packages/pluggableWidgets/maps-web/src/Maps.tsx, packages/pluggableWidgets/maps-web/src/components/GoogleMap.tsx, packages/pluggableWidgets/maps-web/src/components/LeafletMap.tsx, packages/pluggableWidgets/maps-web/src/components/__tests__/__snapshots__/LeafletMap.spec.ts.snap, packages/pluggableWidgets/maps-web/typings/MapsProps.d.ts, packages/tools/pluggable-widgets-tools/configs/rollup.config.js, packages/tools/pluggable-widgets-tools/package.json, packages/tools/pluggable-widgets-tools/test-config/assetsTransformer.js, packages/tools/pluggable-widgets-tools/test-config/jest.config.js
There was an issue in the Openstreet Map configuration that made it impossible to show any marker, neither the default or a custom one. 
Initially we thought it was a rollup config issue. I couldn't get it working through rollup. But from my understanding even if we managed to make `node_modules/leaflet/dist` include the `images/` folder, it might not solve this because of the CSS url reference wasn't resolved properly. Instead, I based the solution on an issue in `react-leaflet`'s issue tracker. Apparently this is a more common issue on their ends, which makes this very prone to error. 
I wrote this in the code as a comment but will repeat it here: instead of the hackish method that are proposed in the linked issue, I decided to just always set the `icon` prop of the Marker component. …
=> [WC-40] Fix default markers for Openstreet Maps and custom markers for all maps

packages/pluggableWidgets/maps-web/src/Maps.editorConfig.ts, packages/pluggableWidgets/maps-web/src/Maps.xml
Right now the general property tab always contains the following block at the end:
But even if you change the map provider and thus need another api token, it will stay:
Open street maps doesn't require an api token, but still shows it. This can be quite confusing for the user since it's not required and not used anyways. So I think removing it should be fine.
Just make sure that every other provider works as expected and there's no regression
=> feat(maps-web): add small description for google maps api token key

packages/pluggableWidgets/maps-web/src/components/LeafletMap.tsx, packages/pluggableWidgets/maps-web/src/components/__tests__/__snapshots__/LeafletMap.spec.ts.snap, packages/pluggableWidgets/maps-web/src/utils/leaflet.ts
Update mapbox styles according to https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/
Relevant for us:
Just check whether mapbox map render normally instead of just grey tiles:
=> [WC-241] update mapbox to new API

packages/pluggableWidgets/accessibility-helper-web/package.json, packages/pluggableWidgets/accessibility-helper-web/src/AccessibilityHelper.editorConfig.ts, packages/pluggableWidgets/accessibility-helper-web/src/package.xml
Similar to #536 and #537, but then for the accessibility helper web widget
Testing tips
Same thing: use the widget, create an error and see whether it's thrown in Mendix 9 version
=> feat(accessibility-helper-web): make consistency checks compatible with Mendix 9

packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.editorConfig.ts, packages/pluggableWidgets/popup-menu-web/src/package.xml
Similar to https://github.com/mendix/widgets-resources/pull/536, but then for popup menu web widget
Same thing: use the widget, create an error and see whether it's thrown in Mendix 9 version
=> feat(popup-menu-web): make consistency checks compatible with Mendix 9

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx
Extra: It fixes a warning being thrown in Studio and Design mode:
`[Data grid 2] Preview error: widget container property 'Empty placeholder' has not been rendered, all widget container properties must be rendered.`
=> fix(datagrid-web): fixing consistency check & warning

packages/customWidgets/calendar-web/package.json, packages/customWidgets/calendar-web/src/components/CalendarContainer.ts, packages/customWidgets/calendar-web/src/package.xml
The start date attribute inside the view tab doesn't work with attributes over association.
- The start date attribute property inside the view tab works now with attributes over association by using the `fetch` API endpoint.
- Bump patch version.
- Test start date attribute inside the view tab with no attribute, direct (context) object attribute and attribute from an associated object.
=> [WC-171] Calendar-web: fix start date attribute inside the view tab

packages/pluggableWidgets/maps-web/src/components/GoogleMap.tsx, packages/pluggableWidgets/maps-web/src/components/__tests__/GoogleMap.spec.ts, packages/pluggableWidgets/maps-web/src/components/__tests__/__snapshots__/GoogleMap.spec.ts.snap
1. Put a map on the home page
2. Go to the home page, see that Google maps works
3. Click on the home icon to refresh the page
4. See that the map is broken
5. Console logs "google api is already presented"
Note:
- This only happened for me on the home page and when refreshing through the icon. If it's a subpage or a browser refresh is performed, everything went fine.
So the setup is as follows. We use a `LoadScript` component to load in the google api script. That components is part of the google map api library that we use and handles a lot of the logic for us. What it's supposed to do is set the google api up when loaded, clean it up on unmount, and render the actual map that we provide. After some pairing with @jordanch we found out that some of the lifecycle methods weren't quite …
=> [WC-255] use useLoadScript instead of LoadScript component to avoid duplicate api load

packages/pluggableWidgets/maps-web/src/package.xml
The `package.json` was already 2.0.0 since a long time (a year), but this was still outdated. With the new changes, everything is umbrella'd under 2.0.0
=> feat(maps-web): new major release version

packages/pluggableWidgets/timeline-web/src/Timeline.editorConfig.ts, packages/pluggableWidgets/timeline-web/typings/TimelineProps.d.ts
This addresses the dropzone issues in custom mode in structure preview by just disabling it.
Version is already 2.0.0
=> [WC-274] fall back to default structure preview when user opts for custom visualization

packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.editorConfig.ts, packages/pluggableWidgets/popup-menu-web/src/package.xml, packages/pluggableWidgets/popup-menu-web/typings/PopupMenuProps.d.ts
This adds structure preview for popup menu. Designs and scope was verified with Chris already.  There is something weird going on with the gray top border for the dropzone that I can't get rid of. Already reported this to @takumagott and they will look into it when they can. But for the scope of contents team it's not a blocker.
=> [WC-26] Implement popup menu web structure preview

packages/customWidgets/calendar-web/package.json, packages/customWidgets/calendar-web/src/components/Calendar.ts, packages/customWidgets/calendar-web/src/components/__tests__/Calendar.spec.ts, packages/customWidgets/calendar-web/src/package.xml
This PR fixed moving events of calendar within same day, even while dragging & dropping or while resizing one event. This also fixed moving events between months in the same day ranges.
This PR introduces the usage of timestamp instead of just comparing the day.
Test click, moving events and resizing them using the Test project in the ticket
=> fix(calendar-web): fixing drop and resize events

packages/customWidgets/calendar-web/src/Calendar.xml, packages/customWidgets/calendar-web/src/components/CalendarContainer.ts, packages/customWidgets/calendar-web/src/utils/data.ts, packages/customWidgets/calendar-web/src/utils/validation.ts, packages/customWidgets/calendar-web/tests/e2e/specs/renderDifferentViews.spec.ts, packages/customWidgets/image-viewer-web/package.json, packages/customWidgets/image-viewer-web/src/ImageViewer.webmodeler.ts, packages/customWidgets/image-viewer-web/src/components/Alert.ts, packages/customWidgets/image-viewer-web/src/components/ImageViewerContainer.ts, packages/customWidgets/image-viewer-web/src/components/__tests__/Alert.spec.ts, packages/customWidgets/image-viewer-web/src/package.xml
The custom widgets calendar-web & image-viewer-web have attributes that support selecting an attribute over association, but didn't properly subscribe to data changes.
calendar-web:
- Remove ability to configure attribute over association attributes for `viewStartAttribute` and `viewEndAttribute`, because this was never implemented.
- Subscribe properly to configured `startDateAttribute` 1-deep association attribute value changes including context object reference changes.
- Improve fetch code for `startDateAttribute`.
- Show an error message when the attribute over association for `startDateAttribute` is more than one level deep.
image-viewer-web:
- Subscribe properly to configured `dynamicUrlAttribute`  1-deep association attribute value changes including context object reference …
=> [WC-272] Fix custom widgets attribute over association support

packages/pluggableWidgets/maps-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/src/components/LeafletMap.tsx, packages/pluggableWidgets/maps-web/src/components/__tests__/__snapshots__/LeafletMap.spec.ts.snap, packages/pluggableWidgets/maps-web/src/ui/Maps.css
- Contains breaking changes ❌ (icons will be moved a bit, but we could argue that it's improved. maps will stay workable for users)
Currently, a custom marker's anchor (the point on the icon that 'points' to the user specified coordinate) is always the top left of the icon. But in most of the cases this does not make sense, so we want to center this.
Unfortunately it isn't possible to change the `LeafletIcon` in any way. 
- Through JavaScript: we can only set the anchor beforehand, but for that we need specific coordinates, for which we need the dimensions …
=> [WC-364]: use CSS transform on custom marker icon using Leaflet.DivIcon to center its anchor

.gitmodules, packages/pluggableWidgets/fieldset-web/tests/e2e/specs/Fieldset.spec.ts, packages/tools/pluggable-widgets-tools/package.json, packages/tools/pluggable-widgets-tools/scripts/e2e.js
- Compatible with: MX 8️⃣
This PR introduces the use of test projects without Atlas resources for e2e tests, so that these projects don't depend on widgets shipped with the Atlas 2 module. This will fix missing Switch widget issues in the e2e tests as switch isn't shipped with the Atlas module anymore.
- Change git submodule references to updated test projects.
Nothing.
=> [WC-452] MX 8 release branch - fix e2e test projects

packages/tools/generator-widget/README.md, packages/tools/generator-widget/generators/app/index.js, packages/tools/generator-widget/generators/app/templates/commons/README.md.ejs, packages/tools/generator-widget/generators/app/templates/packages/package_native.json.ejs, packages/tools/generator-widget/generators/app/templates/packages/package_web.json.ejs, packages/tools/generator-widget/package.json, packages/tools/pluggable-widgets-tools/README.md, packages/tools/pluggable-widgets-tools/package.json
- Contains tests ✅ 
- Compatible with: MX 8️⃣
[Backport of #596]
This PR fixes failing `npm install` executions when scaffolding a widget project with the widget generator with NPM v7.x.x. It also explains users in the readme of generated widget projects how to install dependencies with NPM v7.x.x. 
These failures occur due to NPM v7.x.x installing peer dependencies inside the `node_modules` folder. Not all dependencies inside pluggable-widgets-tools share the same React dependency leading into an unresolvable dependency tree.
- Execute `npm install` with the command line flag `--legacy-peer-deps`. This ensures pluggable-widgets-tools dependencies install correctly with NPM v7.x.x. The flag is ignored by lower versions of NPM.
- Add …
=> [WC-381] Widget generator: fix NPM v7.x.x peer dependency install issue (backport)

packages/pluggableWidgets/barcode-scanner-web/package.json, packages/pluggableWidgets/barcode-scanner-web/rollup.config.js, packages/pluggableWidgets/barcode-scanner-web/src/hooks/useCodeScanner.tsx
See JIRA issue: there were a few console.warns that end up in the studio mendix pro console, which is not what we want.
- Do not support an experimental feature
- Replace specific console.warns
1. Start app with barcode scanner widget
2. Go to the app and open the barcode widget
3. Observe in Mendix SP that no warnings are logged
=> [WC-474] Get rid of studio pro errors console.warned by @zxing/library

packages/customWidgets/calendar-web/package.json, packages/customWidgets/calendar-web/src/components/CalendarContainer.ts, packages/customWidgets/calendar-web/src/package.xml
- Cross-browser compatible ❌
Avoid events arriving from other widgets to appear in the calendar.
Only added a check if the event existed before.
Test drag and drop between days/same day, also resize. And try to drop into another calendar
=> fix(calendar-web): fixing calendar drop events between different widgets

packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/__tests__/PopupMenu.spec.ts, packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx, packages/pluggableWidgets/popup-menu-web/src/package.xml
This PR fixes the onclick events of pop-up menu if it was modeled inside a parent containing also an onclick event like clickable container or data grid v2.
Just added preventDefault and stopPropagation to avoid the event of the parent to be triggered.
--
=> fix(popup-menu-web): fixing onclick while inside a parent containing onclick

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/CHANGELOM.md, packages/pluggableWidgets/datagrid-web/src/components/ColumnResizer.tsx, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Header.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/utils/__tests__/settings.spec.ts, packages/pluggableWidgets/datagrid-web/src/utils/settings.ts
Fix the on change behavior for the settings. It was triggering too much changes while resizing a column or applying any other change like sorting/reordering/hiding.
We changed the behavior of the custom hook.
Please use the mpk attached to the ticket to test.
Thanks @Keraito for the useful help
=> fix(datagrid-web): fixing on change settings being triggered too often

packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx, packages/pluggableWidgets/accordion-web/src/components/Accordion.tsx, packages/pluggableWidgets/accordion-web/src/ui/accordion-main.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_accordion.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/widgets/_accordion.scss
- Contains Atlas changes ✅ 
This PR introduces a design mode for the accordion web widget.
- Add design mode.
- Fix border radius.
Test design mode in Studio (different browsers) and Studio Pro with functional styles only and Atlas styles enabled.
=> [WC-408] Accordion web - Add design mode

packages/pluggableWidgets/datagrid-web/src/Datagrid.xml
Moving advanced group to a new tab and as the last tab.
Why? It was causing confusion to users, we've received some feedbacks about it.
Just xml
--
=> [WC-559] Data grid: moving advanced group to last tab

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Header.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Header.spec.tsx.snap
Fix the column header height when the caption is empty.
-
-
=> fix(datagrid-web): fixing header size when empty

packages/pluggableWidgets/image-viewer-web/tests/e2e/objects/constants.ts, packages/pluggableWidgets/image-viewer-web/tests/e2e/objects/imageViewer.widget.ts, packages/pluggableWidgets/image-viewer-web/tests/e2e/specs/onClick.spec.ts
- Cross-browser compatible  ❌
Enable the on click actions test spec again for image viewer widget.
Fixed the test spec and test project to works with new image viewer widget.
=> [WC-557] Enable on click test spec for image viewer

packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
This PR fixes the design mode preview for custom header icons configured with an image.
- Change code to assume preview icon props contain a `WebIcon` or `null`.
Configuring a custom icon, expandIcon and collapseIcon with a glyph or image.
=> [WC-577] Accordion web - Fix design mode preview image header icon

packages/customWidgets/calendar-web/CHANGELOG.md, packages/customWidgets/calendar-web/package.json, packages/customWidgets/calendar-web/src/Calendar.webmodeler.ts, packages/customWidgets/calendar-web/src/Calendar.xml, packages/customWidgets/calendar-web/src/components/Calendar.ts, packages/customWidgets/calendar-web/src/components/CalendarContainer.ts, packages/customWidgets/calendar-web/src/components/__tests__/Calendar.spec.ts, packages/customWidgets/calendar-web/src/components/__tests__/Toobar.spec.ts, packages/customWidgets/calendar-web/src/package.xml
Removing truncated events options due to React 17, this causes the events to go through the day view instead of open the popup. @cjfhodges agreed with the solution.
--
--
=> [WC-582] Calendar: removing truncated events

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
- Contains unit tests ❌ 
- Cross-browser compatible  ❌
This PR fix the default sort order not being applied.
Test using the sort order in the data source.
=> [WC-623] Fix datagrid 2 default sorting issue

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/VideoPlayer.editorConfig.ts, packages/pluggableWidgets/video-player-web/src/VideoPlayer.editorPreview.tsx, packages/pluggableWidgets/video-player-web/src/VideoPlayer.tsx, packages/pluggableWidgets/video-player-web/src/VideoPlayer.xml, packages/pluggableWidgets/video-player-web/src/components/Dailymotion.tsx, packages/pluggableWidgets/video-player-web/src/components/Html5.tsx, packages/pluggableWidgets/video-player-web/src/components/SizeContainer.tsx, packages/pluggableWidgets/video-player-web/src/components/Vimeo.tsx, packages/pluggableWidgets/video-player-web/src/components/Youtube.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Dailymotion.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Html5.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/SizeContainer.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Utils.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Vimeo.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Youtube.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Dailymotion.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Html5.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/SizeContainer.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Video.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Vimeo.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Youtube.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/ui/VideoPlayer.css, packages/pluggableWidgets/video-player-web/src/utils/Utils.ts, packages/pluggableWidgets/video-player-web/typings/VideoPlayerProps.d.ts
This PR adds an aspect ratio options widget configuration property and improves the way dimensions are enforced on the video element.
- Add aspect ratio options widget configuration property.
- Rehaul setting dimensions on video player.
- Remove natural video aspect ratio calculation via third party.
Test all dimension options for all video player options as the underlying dimension enforcement has changed.
=> [WC-528] Video player web - Improve dimensions tab

packages/pluggableWidgets/datagrid-web/tests/e2e/specs/DataGrid.spec.ts
- Is accessible ✅ ❌
- Cross-browser compatible ✅ ❌
Add data source sorting order test to verify the expected behavior when you're using this option in a datagrid 2 widget.
Test project has been changed to enable this option.
=> [WC-624] Add data source sorting order test in datagrid 2

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/VideoPlayer.editorConfig.ts, packages/pluggableWidgets/video-player-web/src/VideoPlayer.tsx, packages/pluggableWidgets/video-player-web/src/VideoPlayer.xml, packages/pluggableWidgets/video-player-web/src/package.xml, packages/pluggableWidgets/video-player-web/tests/e2e/specs/VideoPlayer.spec.ts, packages/pluggableWidgets/video-player-web/typings/VideoPlayerProps.d.ts
- Contains breaking changes ✅ 
~Prepare a major release 2.0.0 for video web.~
This will now only be a minor where we add options to configure links through text templates.
- ~Structure preview~
- ~move video URL and poster URL to string templates~
- add options to configure video URL and poster URL with text templates
- I assume the text templates should not change the e2e specs too much except maybe that the widgets need to be configured again. But the result should be the same.
- Structure preview is showing up appropriately.
=> [WC-529] add text template properties for urls

packages/pluggableWidgets/accordion-web/CHANGELOG.md, packages/pluggableWidgets/accordion-web/src/Accordion.editorConfig.ts, packages/pluggableWidgets/accordion-web/src/Accordion.tsx, packages/pluggableWidgets/accordion-web/src/Accordion.xml, packages/pluggableWidgets/accordion-web/src/components/Accordion.tsx, packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx, packages/pluggableWidgets/accordion-web/src/components/Header.tsx, packages/pluggableWidgets/accordion-web/src/components/__tests__/Accordion.spec.tsx, packages/pluggableWidgets/accordion-web/src/components/__tests__/AccordionGroup.spec.tsx, packages/pluggableWidgets/accordion-web/src/components/__tests__/Header.spec.tsx, packages/pluggableWidgets/accordion-web/src/components/__tests__/__snapshots__/Accordion.spec.tsx.snap, packages/pluggableWidgets/accordion-web/src/components/__tests__/__snapshots__/Header.spec.tsx.snap, packages/pluggableWidgets/accordion-web/typings/AccordionProps.d.ts
- Comply with designs ✅ ❌
Introduce the remainder of advanced mode features of accordion web.
- Add a widget property to configure the render mode of the header text.
- Add widget properties to influence the initial collapsed state for a group.
- Add a widget property to trigger an action when the widget collapse state changes.
- Add consistency check for single expanded mode & multiple start expanded configuration.
Test the new properties.
=> [WC-402 ] Accordion web - Add remaining advanced mode features

packages/pluggableWidgets/tree-view-web/src/TreeView.editorConfig.ts, packages/pluggableWidgets/tree-view-web/src/TreeView.tsx, packages/pluggableWidgets/tree-view-web/src/TreeView.xml, packages/pluggableWidgets/tree-view-web/src/components/Icon.tsx, packages/pluggableWidgets/tree-view-web/src/components/TreeView.tsx, packages/pluggableWidgets/tree-view-web/src/components/__tests__/TreeView.spec.tsx, packages/pluggableWidgets/tree-view-web/src/ui/TreeView.scss, packages/pluggableWidgets/tree-view-web/typings/TreeViewProps.d.ts
- Make headers composable, exactly the same as accordion (2nd commit)
- allow configuration of custom icons and placement, similar to accordion (4th commit)
- group General widget properties into another group for Studio (3rd commit)
=> [WC-651] Make headers composable and introduce custom icons

packages/pluggableWidgets/tree-view-web/src/TreeView.editorConfig.ts, packages/pluggableWidgets/tree-view-web/src/TreeView.tsx, packages/pluggableWidgets/tree-view-web/src/TreeView.xml, packages/pluggableWidgets/tree-view-web/src/assets/loading-circle.svg, packages/pluggableWidgets/tree-view-web/src/components/TreeView.tsx, packages/pluggableWidgets/tree-view-web/src/components/TreeViewBranchContext.ts, packages/pluggableWidgets/tree-view-web/src/components/__tests__/TreeView.spec.tsx, packages/pluggableWidgets/tree-view-web/src/ui/TreeView.scss, packages/pluggableWidgets/tree-view-web/typings/TreeViewProps.d.ts
Adds lazy loading to tree view nodes behind a widget property and adds a placeholder loading state.
=> [WC-354] Add lazy loading for tree view nodes

packages/customWidgets/rich-text-web/src/components/RichText.ts
A Quill js bug causes to steal the focus, this was reported in the issue https://github.com/mendixlabs/rich-text/issues/32
The solution is to disable the editor before updating the content, as suggested in the https://github.com/quilljs/quill/issues/2156#issuecomment-619530283
=> Disabled quill before update

packages/jsActions/nanoflow-actions-web/CHANGELOG.md, packages/jsActions/nanoflow-actions-web/package.json, packages/jsActions/nanoflow-actions-web/src/TakePicture.ts
- Fix confirmation screen not reacting to confirming (now it hides the button and pauses the feed)
- Add possibility to choose picture quality
- Hide buttons when making a picture and it's loading (regardless of whether confirmation screen will be shown)
All the above cases and also whether trying the same flow multiple times works properly (had a few moments where the UI would be weird after repeating the same flow).
=> [WC-635 & WC-636] Improve take a picture action

packages/pluggableWidgets/accordion-web/CHANGELOG.md, packages/pluggableWidgets/accordion-web/package.json, packages/pluggableWidgets/accordion-web/src/Accordion.editorConfig.ts, packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx, packages/pluggableWidgets/accordion-web/src/package.xml
Fix structure preview and Studio/Design mode when there is no group configured. Before it was showing just a blank canvas making the usage very difficult.
Bonus: In order to reach the general properties of accordion I added the same header as Gallery and Data Grid as the Accordion uses Selectable objects for the list items (groups).
--
General DX of Accordion.
=> [WC-709] Accordion - Fix previews with no data

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/VideoPlayer.editorConfig.ts, packages/pluggableWidgets/video-player-web/src/VideoPlayer.editorPreview.tsx, packages/pluggableWidgets/video-player-web/src/VideoPlayer.xml, packages/pluggableWidgets/video-player-web/src/package.xml, packages/pluggableWidgets/video-player-web/src/ui/VideoPlayerPreview.css
Rename properties from Link to URL, remove clicks from the video tag (In Studio) to prevent enter fullscreen when double clicking or play the video when single clicking and adding missing group for controls.
--
Studio + Studio Pro smoke test
=> [WC-702] Video Player - Renaming properties

packages/pluggableWidgets/image-web/package.json, packages/pluggableWidgets/image-web/src/Image.editorConfig.ts, packages/pluggableWidgets/image-web/src/Image.editorPreview.tsx, packages/pluggableWidgets/image-web/typings/ImageProps.d.ts
- Contains breaking changes ✅ 
- Compatible with: MX 9.5 and above
This PR introduces a check whether the image property is configured when the datasource property is set to image.
- Add consistency check.
- Requires 9.5 or aboe, because system images cause empty string preview prop in lower versions, which causes the consistency check to fail when the field is actually configured.
- Updated test project to prevent consistency check failures.
Studio and Studio Pro consistency checking.
E2e tests are disabled due to id change when renaming the widget. I created a story to reconfigure the whole test project.
=> [WC-579] Image (web) - add image configured check

packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas-responsive.scss
- Contains Atlas changes ✅
- Fix overlapping and broken navigationtree expansion hover popup
- The problem was that the left offside was always set to 52px. This is fine for the second level as the first level is always that wide, but the second level is then visually restricted as the third level is only offset by 52px. For the third level, we now offset by 100% of the element, which lets the second level expand horizontally entirely.
- Also made sure that the third level is only opened when the second level is hovered, instead of showing all the …
=> [WC-704] Fix navigationtree hover popup

packages/pluggableWidgets/accordion-web/CHANGELOG.md, packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx, packages/pluggableWidgets/accordion-web/src/Accordion.tsx, packages/pluggableWidgets/accordion-web/src/Accordion.xml, packages/pluggableWidgets/accordion-web/src/utils/__tests__/__snapshots__/iconGenerator.spec.ts.snap, packages/pluggableWidgets/accordion-web/src/utils/__tests__/iconGenerator.spec.ts, packages/pluggableWidgets/accordion-web/src/utils/iconGenerator.tsx, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/gallery-web/src/Gallery.editorConfig.ts, packages/pluggableWidgets/gallery-web/src/Gallery.xml, packages/pluggableWidgets/maps-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/src/Maps.tsx, packages/pluggableWidgets/maps-web/src/Maps.xml, packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.editorConfig.ts, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.xml, packages/pluggableWidgets/tree-node-web/src/TreeNode.editorPreview.tsx, packages/pluggableWidgets/tree-node-web/src/TreeNode.tsx, packages/pluggableWidgets/tree-node-web/src/TreeNode.xml
Rename advanced property & remove its usage in browser executed code. Also align advanced mode properties across widgets and move property group to tabs for popup menu in Studio.
Verify advanced mode properties work.
Accordion / Tree node: icon behaviour in advanced and not advanced mode
Maps: test whether API keys still work and show current location feature.
=> [WC-753] Advanced options widgets - Rename advanced property & remove its usage in browser executed code

packages/pluggableWidgets/image-web/src/components/Image/index.tsx, packages/pluggableWidgets/image-web/src/components/Image/ui.tsx, packages/pluggableWidgets/image-web/src/components/__tests__/__snapshots__/Image.spec.tsx.snap
**_Please remove unnecessary emojis and sections and this comment before proceeding_**
- Aligning with the previous implementation of static and dynamic image, adding the `img-thumbnail` classname to the image to load the appropriate stylings.
- Also fix the URL parsing in design preview, since there it doesn't get a proper URL.
=> [WC-501] fix thumbnail url for design preview and thumbnail className

packages/pluggableWidgets/accessibility-helper-web/src/AccessibilityHelper.xml, packages/pluggableWidgets/accordion-web/src/Accordion.xml, packages/pluggableWidgets/badge-button-web/src/BadgeButton.xml, packages/pluggableWidgets/badge-web/src/Badge.xml, packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.xml, packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.xml, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.xml, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.xml, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.xml, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/dropdown-sort-web/src/DropdownSort.xml, packages/pluggableWidgets/fieldset-web/src/Fieldset.xml, packages/pluggableWidgets/gallery-web/src/Gallery.xml, packages/pluggableWidgets/image-web/src/Image.xml, packages/pluggableWidgets/maps-web/src/Maps.xml, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.xml, packages/pluggableWidgets/progress-bar-web/src/ProgressBar.xml, packages/pluggableWidgets/progress-circle-web/src/ProgressCircle.xml, packages/pluggableWidgets/switch-web/src/Switch.xml, packages/pluggableWidgets/timeline-web/src/Timeline.xml, packages/pluggableWidgets/tree-node-web/src/TreeNode.xml, packages/pluggableWidgets/video-player-web/src/VideoPlayer.xml
Add help URL in order to redirect the user to the correct documentation when clicking the `?` button in the bottom of the widgets or pressing F1.
Added helpUrl property to the missing widgets.
Trigger in the `?` button and pressing F1. In studio it should appear only the `?` button.
=> [WC-773] Add help-url to Web Pluggable Widgets

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/VideoPlayer.xml, packages/pluggableWidgets/video-player-web/src/package.xml
Changed default value to dynamic
- Contains Atlas changes  ❌
Change the default data source type to be dynamic instead of expression.
--
General usage of the widget
=> [WC-874] Video Player - Change default data source to dynamic

packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.editorConfig.ts, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.xml, packages/pluggableWidgets/popup-menu-web/src/__tests__/PopupMenu.spec.ts, packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx, packages/pluggableWidgets/popup-menu-web/src/package.xml, packages/pluggableWidgets/popup-menu-web/typings/PopupMenuProps.d.ts
- Comply with designs ❌
The purpose is to add functionality for end-users to toggle visibility of items inside popup depending on the situation.
I added a visibility expression property on the pop-up widget for basic and custom items.
Added consistency check when divider type of item is selected.
Added unit tests for both cases (hidden/visible)
I kept the previous configuration, but it'll be good to test if this widget works on previously created popups.
- Bumped version to **3.1.0**
=> [WC-246] Added visibility option for popup items

packages/modules/data-widgets/src/themesource/datawidgets/web/datagrid.scss, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
Add the possibility to wrap texts when widgets are not being used as the content of a column.
Added extra class in the data-widgets module folder and a property for each column.
Tests with widgets and pure texts should be done.
It also works with Text widgets with different renderings like span, p, h1 when placed directly inside the columns (not inside containers).
=> [WC-828] Data Grid - Add design property to wrap texts

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/utils/__tests__/useCellRenderer.spec.ts, packages/pluggableWidgets/datagrid-web/src/utils/useCellRenderer.tsx, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
- Works in Android ✅ ❌
- Works in iOS ✅ ❌
- Works in Tablet ✅ ❌
- Comply with PM's requirements (in progress)
Add new property to Datagrid v2
New `Tooltip` property, which allow you to control text that will be seen when hovering cell
You should be able to set tooltip for column in datagrid.
@leonardomendix, attached project package for test to the story.
=> [WC-827] Configurable tooltips for columns in Datagrid 2

packages/pluggableWidgets/range-slider-web/package.json, packages/pluggableWidgets/range-slider-web/tests/e2e/objects/rangeSlider.widget.ts
Re-enable slider e2e test of range slider widget.
Changed selector to work with new widget.
=> [WC-927]: Re-enable range slider e2e test

packages/tools/pluggable-widgets-tools/CHANGELOG.md, packages/tools/pluggable-widgets-tools/package.json
Backporting #1212 to 8.18.x branch
=> [WC-956] Fix hacked colors library in PIW-tools 8.18

packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml
When using Dropdown filter inside Data grid 2 header or Gallery and selecting multiple attributes (Enumeration or Boolean), the filter was being applied only if there was no invalid values selected, which shouldn't be the case. This PR fixes the behavior of Dropdown filter and applies the filter conditions for the attribute that contains the values.
Changed how the filter conditions were being applied. Removed a check if there was some invalid value (return undefined 😵‍💫 )
Test using Data grid and Gallery. While testing Data grid, it should also be verified if normal filtering using data …
=> [WC-969] fix(datagrid-dropdown-filter-web): fixing filtering using multiple attributes

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
When using Windows browsers the checkbox inside each item of column selector accepts events, then triggering it doesnt force the checkbox to behave as expected as the events are in the `li`. This fixes this issue.
Added pointerEvents none to the radio button input.
Usage of column selector on Windows/Mac and also tests using keyboard.
=> [WC-960] fix(datagrid-web): column selector checkbox in windows machines

packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx, packages/pluggableWidgets/popup-menu-web/src/package.xml
While using Firefox on windows the element being passed does not contain parentElement, so it throws an error as the function is expecting a parent (It was not counted while developing the function). Note: Firefox uses `<html class="dj_gecko dj_ff95 dj_contentbox" lang="en-US">` which does not contains a parent. So this PR fixes the function.
Added extra check to verify if the current element contains a parent before iterate again.
General usage on Max/Windows and multiple browsers.
=> [WC-959] fix(popup-menu-web): fixing correctPosition function

packages/pluggableWidgets/maps-web/tests/e2e/specs/google.spec.ts, packages/pluggableWidgets/maps-web/tests/e2e/specs/here.spec.ts, packages/pluggableWidgets/maps-web/tests/e2e/specs/mapbox.spec.ts, packages/pluggableWidgets/maps-web/tests/e2e/specs/openstreet.spec.ts
Today, the screenshot for maps is very sensitive, and we have some elements being rendered that don't matter for our test, and it's causing some flaky tests. Increasing the threshold should fix that.
Changed screenshot element check threshold.
=> [WC-1006]: Change maps screenshot threshold

packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/package.xml, packages/pluggableWidgets/popup-menu-web/src/utils/document.ts
Fix the issue described in WC-959 and WC-975 regarding the popup menu being shown off screen when placed on the edge of the page and configured in the direction outside the page. The problem on Firefox windows was that when the user toggles the popup menu, the display is changed from `flex` to `none`. When that happens, it was put on the page and actually increases the size of the page (confirmed by the introduced scrollbars). 
The problem is that our current implementation uses `window.innerHeight` and `window.innerWidth` to …
=> [WC-975]: use client resolutions instead of inner to fix offscreen position

packages/pluggableWidgets/rich-text-web/rollup.config.js, packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/components/MainEditor.tsx, packages/pluggableWidgets/rich-text-web/src/components/RichText.tsx
- Fix CSS styling issue in Firefox
- Fix "Event -> On key press" action execution
- Fix focus reset issue
- `rollup.config.js` add regexp to copy content of critical editor dependencies
- change `dispatchEvent` function to react on "key" actions
- change `components/ReactText.tsx` to update value without re-rendering
- RichText focus
- RichtText in firefox
- RichtText "On key press" event
=> [WC-1021] Fix RichText in firefox

packages/pluggableWidgets/rich-text-web/src/RichText.editorPreview.tsx, packages/pluggableWidgets/rich-text-web/src/ui/RichTextEditorPreview.scss
Add design mode preview for RichText
- this PR introduces `preview` implementation for RichText (which was missing)
- RichText widget preview in design mode
=> [WC-1043] Add design-mode preview for RichText

packages/pluggableWidgets/carousel-web/src/Carousel.editorConfig.ts, packages/pluggableWidgets/carousel-web/src/ui/dot_blue.svg, packages/pluggableWidgets/carousel-web/src/ui/dot_empty.svg, packages/pluggableWidgets/carousel-web/src/ui/dot_grey.svg
Adding structure preview for new version of carousel
Added three type of dots. Blue, Transparent and Grey.
`Blue` is the active one, `grey` unselected one and `transparent` is for making space between `blue` and `grey` dots.
It was not possible to do with current structure mode api's, because when I use padding in a container it was breaking svg images, instead of dot's they became rectangular.
`...neutralDots,
...neutralDots`
I copied the variable because somehow it wasn't working with function. If anyone knows why just let me …
=> [WC-1061] Structure preview for Carousel

packages/pluggableWidgets/carousel-web/rollup.config.js, packages/tools/pluggable-widgets-tools/configs/rollup.config.js
Basically reviving #1375, this was specifically done for Carousel widget, since we import CSS from `swiper` which has 2 inline fonts.
=> [WC-1048] extract assets from CSS into assets folder for carousel

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/VideoPlayer.tsx, packages/pluggableWidgets/video-player-web/src/package.xml
- Compatible with:  9️⃣
- Fix Video Player issue with browser history being broken after updating player URL
- the `key` prop was added to the player to prevent unexpected history changes 
- Check attached slack video
=> [WC-1084] Remount video player on url change to not break history

packages/modules/data-widgets/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/cypress/integration/DataGrid.spec.js, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
- Fix column hiding behavior in datagrid 
- Added extra check to onClick handler to prevent hiding of last visible column
- Column selector
=> [WC-1086] Add last visible column check to onClick handler in column selector

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/components/DatePicker.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/DatePicker.spec.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-date-filter-web/src/utils/utils.ts
- Replace regex with function as current regex syntax not yet supported by Safari
- Replace regex with similar function logic is changed bit, but result is the same.
- You should be able to type date in "long format" (e.g. 02/03/2022) and date filter should accept it.
=> [WC-1093] Replace regex with function

packages/modules/data-widgets/src/themesource/datawidgets/web/datagrid-filters.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/datagrid.scss
… on top of it
Fix the issue with icons appearing on top of headers in dg2.
The issue was about icons having different positioning than table div itselfs, so the reasonable change to prevent all kind of cases was to add minimal z-index value for table headers.
Check whether it works for icons, texts and other items(buttons, dropdowns,etc.)
In a worst case this can be configured by user itself, if for example dropdown appears on top of header he/she can simply change z-index in his css configuration.
Please let me know if I need to update change-logs …
=> [WC-1083] Fix glyphicon issue on dg2

scripts/release/createWebModules.js
- Fix modules automation script
- The updateChangelogs function was missing argument
=> fix: automation/web-modules: add missing widgetsFolders arg to updateChangelogs fn

packages/modules/data-widgets/src/themesource/datawidgets/web/datagrid.scss, packages/pluggableWidgets/datagrid-web/src/utils/__tests__/useCellRenderer.spec.ts, packages/pluggableWidgets/datagrid-web/src/utils/useCellRenderer.tsx
- Contains breaking changes  ❌
- Contains Atlas changes ✅
Fix alignment of elements of custom content placed in datagrid cells.
Widgets rendered as custom content correctly taking whole space of a cell.
=> [WC-829] fix(datagrid-web): fix cell size for custom content

packages/pluggableWidgets/slider-web/CHANGELOG.md, packages/pluggableWidgets/slider-web/src/ui/Slider.scss
- Fix style issue for Slider
- We set root styles for Slider to be `flex-grow: 1` by default
- Enable "Show label" property for sldier
- Expected: slider width should be equal to available space
=> [WC-1107] Fix issue with slider flex-grow

packages/pluggableWidgets/dropdown-sort-web/cypress/integration/DropDownSort.spec.js, packages/pluggableWidgets/dropdown-sort-web/cypress/plugins/index.js, packages/pluggableWidgets/dropdown-sort-web/cypress/support/index.js, packages/pluggableWidgets/dropdown-sort-web/package.json
Add e2e test for dropdown-sort-web.
Added specs using Cypress.
=> [WC-1139] Add e2e test for dropdown-sort-web

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/Gallery.spec.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/__snapshots__/Gallery.spec.tsx.snap, packages/pluggableWidgets/gallery-web/src/package.xml, packages/pluggableWidgets/gallery-web/tsconfig.json
Purpose is to remove `widget-gallery-filter` element from dom if there is no filters.
Added filters count variable to make it simple to understand whether is there a filter or not.
If element exist on DOM or not.
Need to add e2e tests as well.
=> [WC-1177] Gallery widget filters container

packages/pluggableWidgets/dropdown-sort-web/cypress/integration/DropDownSort.spec.js
Fix a test with the dropdown sort, failing on CI only.
Added a new wait to get the correct values in the expect.
=> Fix dropdown sort e2e test failing

packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/datagrid.scss, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml
- Contains unit tests  ❌
- Contains breaking changes  ❌
- Contains e2e tests ✅ ❌
Fix filter widgets overflowing header cells.
=> fix(datagrid-web): fix filter widgets layout

packages/pluggableWidgets/datagrid-date-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/DatagridDateFilter.spec.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/__tests__/DataGridDropdownFilter.spec.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/components/__tests__/DatagridNumberFilter.spec.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/components/__tests__/__snapshots__/FilterComponent.spec.tsx.snap, packages/pluggableWidgets/datagrid-text-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/components/__tests__/DatagridTextFilter.spec.tsx
- Fix issue with `defaultValue` prop and filters behaviour
- Now it's possible to control filter value with `defaultValue` prop. Now it fully synced.
- In our case if widget has defaultValue setting, you should be able to change value of this setting and observe changes in the component value.
=> [WC-1208] fix: sync value with defaultValue in datagrid filters

packages/pluggableWidgets/rich-text-web/cypress/integration/RichText.spec.js
-   PR title properly formatted (`[XX-000]: description`)? ❌
-   Contains e2e tests ✅ 
-   [ ] Bug fix
-   [x] Other (test)
Sometimes we're getting an uncaught exception when running rich text e2e tests. That happened because the page is not ready and we're trying to get the body from this page. To fix that I prevent this exception of stopping the test, then in the next retry the page will be available.
Added a configuration to prevent Cypress from failing the test in case of this uncaught exception.
=> Fix flaky rich text e2e test 

packages/pluggableWidgets/tooltip-web/CHANGELOG.md, packages/pluggableWidgets/tooltip-web/package.json, packages/pluggableWidgets/tooltip-web/src/components/Tooltip.tsx, packages/pluggableWidgets/tooltip-web/src/package.xml, packages/pluggableWidgets/tooltip-web/src/ui/Tooltip.scss
-   Contains unit tests ❌ 
-   Contains breaking changes ❌
-   Contains Atlas changes ❌
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣
-   Did you update version and changelog? ✅ 
-   PR title properly formatted (`[XX-000]: description`)? ✅ 
-   Contains e2e tests ✅❌
-   Is accessible ✅ ❌
-   Compatible with Studio ✅ ❌
-   Cross-browser compatible ✅ ❌
-   [x] Bug fix
Fix a UI issue reproducable on a specific fallback position configuration (right) of Tooltip widget, ('top' in Studio, 'right' in fallback properties)
=> [WC-1094]: fix styling of react-popper arrow

packages/modules/data-widgets/package.json
-   Contains unit tests ❌
-   Contains breaking changes ❌
-   Contains Atlas changes ❌
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣
-   Did you update version and changelog? ✅ 
-   PR title properly formatted (`[XX-000]: description`)? ✅ ❌
-   Contains e2e tests ❌
-   Is accessible ❌
-   Compatible with Studio ✅ 
-   Cross-browser compatible ✅ 
-   [ ] Bug fix
-   [x] Other (version bump)
Changing version of data-widgets module from 2.5.4 to 2.5.5
=> [WC-1256]: data-widgets version bump to 2.5.5

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/FilterComponent.spec.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml
Closes WC-1157
-   Contains unit tests ✅
-   Contains breaking changes ❌
-   Contains Atlas changes ❌
-   Compatible with: 9️⃣
-   Did you update version and changelog? ✅
-   PR title properly formatted (`[XX-000]: description`)? ✅
-   Contains e2e tests ✅
-   Is accessible ❌
-   Compatible with Studio ✅
-   Cross-browser compatible ✅
-   [x] Bug fix
DateFilter had infinite loop because of changes introduced in DateFilter v2.4.1. To solve this issue we compare incoming date value not by reference but by object value.
FilterComponent: When defaultValue get new value instead of
comparing object itself we comparing it's value
- DG2 with DateFilter where DateFilter keeps it's value between user session
=> [WC-1321] Date filter causing multiple requests
