mendix/widgets-resources

packages-web/maps/package-lock.json, packages-web/maps/package.json, packages-web/maps/src/package.xml
=> fix(maps-web): bumping version

packages-native/activity-indicator/package.json, packages-native/animation/package.json, packages-native/app-events/package.json, packages-native/badge/package.json, packages-native/barcode-scanner/package.json, packages-native/color-picker/package.json, packages-native/feedback/package.json, packages-native/floating-action-button/package.json, packages-native/intro-screen/package.json, packages-native/listview-swipe/package.json, packages-native/maps/package.json, packages-native/notifications/package.json, packages-native/progress-bar/package.json, packages-native/progress-circle/package.json, packages-native/qr-code/package.json, packages-native/range-slider/package.json, packages-native/rating/package.json, packages-native/slider/package.json, packages-native/toggle-buttons/package.json, packages-native/video-player/package.json, packages-native/web-view/package.json, packages-web/badge-button/package.json, packages-web/video-player/package.json
Improve npm scripts of pluggable widgets:
- e2e test scripts
- dev scripts
=> Mono repo fixes

.travis.yml, detox/jest.startup.js, detox/package.json, detox/specs/activityIndicator.spec.ts, detox/specs/badge.spec.ts, detox/specs/elements/ListViewSwipe.ts, detox/specs/feedback.spec.ts, detox/specs/floatingActionButton.spec.ts, detox/specs/listviewSwipe.spec.ts, detox/specs/progressCircle.spec.ts, detox/specs/rating.spec.ts
Requires https://github.com/mendix/widgets-resources/pull/90 to be merged before
=> [Detox] Updating ids and adding Rating tests

packages-web/badge/package-lock.json, packages-web/badge/package.json, packages-web/badge/tests/e2e/specs/onClick.spec.ts
Add nightly branch to test project
=> chore(badge): add nightly branch to test project

README.md, packages-native/app-events/package.json, packages-native/app-events/src/package.xml, packages-native/intro-screen/package.json, packages-native/intro-screen/src/package.xml
Note:
Components already has been released, no need to test.
=> fix(): bump versions and add readme for releasing

packages-web/calendar/package-lock.json, packages-web/calendar/package.json, packages-web/calendar/src/Calendar.webmodeler.ts, packages-web/calendar/src/components/CalendarContainer.ts, packages-web/calendar/src/package.xml, packages-web/calendar/src/utils/data.ts, packages-web/calendar/src/utils/namespaces.ts, packages-web/calendar/src/utils/style.ts, packages-web/calendar/src/utils/validation.ts, packages-web/calendar/webpack.config.dev.js, packages-web/calendar/webpack.config.prod.js
- Fixing on select time slots (times were not being respected) in daily, weekly and monthly view
- Removing deprecation warning
- Fixing preview in Studio/Studio Pro
=> Fixing calendar issues

packages-common/nanoflow-commons/src/client/ShowConfirmation.ts, packages-native/actions/src/camera/TakePicture.ts
Includes following:
- Fixes #191 ShowConfirmation: Allow change of default title 'Confirmation' in native
- Fixes #189 TakePicture: Optionally allow image width/height to be stored on the Mendix object
I could not build them, npm install and npm run build use rm command. The changes are as I tested them in my own projects.
=> Enhancements to ShowConfirmation and TakePicture

packages-native/actions/src/camera/TakePictureAdvanced.ts
Sanity check for @mgroeneweg previous PR when he introduced a JS Action for Take a picture with meta data.
Thanks again for you PR @mgroeneweg
=> fix(actions): fixing take picture advanced

packages-web/video-player/package.json, packages-web/video-player/src/components/Html5.tsx, packages-web/video-player/src/components/__tests__/__snapshots__/Html5.spec.tsx.snap, packages-web/video-player/src/components/__tests__/__snapshots__/Video.spec.tsx.snap, packages-web/video-player/src/package.xml
In this PR we fixed an issue with video player where the poster was being replaced even before press play. Fixes ticket #103534
=> fix(videoplayer): fixing poster issue

packages-native/actions/src/camera/TakePicture.ts, packages-native/actions/src/camera/TakePictureAdvanced.ts
In this PR we fixed a problem where the filename was not being stored.
=> [WT-2637] TakePicture Action - Adding filename

packages-common/piw-utils/src/typings/PageEditor.ts, packages-common/piw-utils/src/utils/PageEditorUtils.ts, packages-web/datagrid/src/components/__tests__/__snapshots__/Table.spec.tsx.snap, packages-web/maps/package.json, packages-web/maps/src/Maps.editorConfig.ts, packages-web/maps/src/Maps.xml, packages-web/maps/typings/MapsProps.d.ts
In this PR we are aligning properties with Designs by Remco and few discussions about how easy is it for Cate with Arjan H. and Danny R.
=> [W] Maps - Align properties with designs

packages-common/pluggable-widgets-tools/scripts/gulp.js
The clean script also removed the development projects
=> Clean script should only rm build & tmp

packages/customWidgets/slider-web/package.json, packages/customWidgets/slider-web/tests/e2e/specs/Slider.spec.ts
When I test locally using docker I am getting that error in the Slider spec: 
`Expected 'left: 33.3333%; right: auto; transform: translateX(-50%);' to be 'left: 33.3333%;'.`
=> test(slider-web): fix slider-web flaky test

packages/tools/pluggable-widgets-tools/configs/webpack.config.common.js, packages/tools/pluggable-widgets-tools/configs/webpack.native.config.js, packages/tools/pluggable-widgets-tools/package.json, packages/tools/utils-react-widgets/configs/webpack.config.dev.js, packages/tools/utils-react-widgets/configs/webpack.config.prod.js
=> fix(pluggable-widgets-tools): fixing copy-webpack-plugin path

packages/customWidgets/calendar-web/package.json, packages/customWidgets/carousel-web/package.json, packages/customWidgets/color-picker-web/package.json, packages/customWidgets/image-viewer-web/package.json, packages/customWidgets/progress-bar-web/package.json, packages/customWidgets/progress-circle-web/package.json, packages/customWidgets/range-slider-web/package.json, packages/customWidgets/rich-text-web/package.json, packages/customWidgets/signature-web/package.json, packages/customWidgets/slider-web/package.json, packages/customWidgets/star-rating-web/package.json, packages/customWidgets/switch-web/package.json, packages/pluggableWidgets/accessibility-helper-web/package.json, packages/pluggableWidgets/badge-web/package.json, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/video-player-web/package.json, packages/tools/pluggable-widgets-tools/bin/mx-scripts.js, packages/tools/pluggable-widgets-tools/test-config/wdio.conf.js
After the packages were restructured, it was necessary to change the path of this option.
=> test: fix wdio conf path in package.json

packages/tools/pluggable-widgets-tools/package.json
Bumping versions was forgotten in PR: https://github.com/mendix/widgets-resources/pull/283
=> Bump PIW tooling versions

packages/pluggableWidgets/maps-native/README.md
=> fix(maps-native): improve readme

packages/pluggableWidgets/floating-action-button-native/package.json, packages/pluggableWidgets/floating-action-button-native/src/FloatingActionButton.tsx, packages/pluggableWidgets/floating-action-button-native/src/__tests__/__snapshots__/FloatingActionButton.spec.tsx.snap, packages/pluggableWidgets/floating-action-button-native/src/package.xml, packages/pluggableWidgets/floating-action-button-native/src/ui/styles.tsx
This PR fixes the problems around border styling for floating action button for native.
=> fix(floating-action-button-native): add new style prop, fix border styling

packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap
In this PR we are:
- Fixing missing dependencies for cell renderer
- Fixing wrong style property causing console errors in dev mode
- Adding missing key for cells
=> fix(datagrid-web): adding missing dependencies and fixing style tag

packages/tools/pluggable-widgets-tools/scripts/e2e.js, packages/tools/pluggable-widgets-tools/scripts/m2ee.yml, packages/tools/pluggable-widgets-tools/scripts/runtime.sh
- Migrating Runtime Docker image from Ubuntu to RHEL
=> Fixing E2E Failing Infra

packages/pluggableWidgets/range-slider-native/package.json, packages/pluggableWidgets/range-slider-native/src/Marker.tsx, packages/pluggableWidgets/range-slider-native/src/RangeSlider.tsx, packages/pluggableWidgets/range-slider-native/src/package.xml, packages/pluggableWidgets/slider-native/package.json, packages/pluggableWidgets/slider-native/src/Marker.tsx, packages/pluggableWidgets/slider-native/src/Slider.tsx, packages/pluggableWidgets/slider-native/src/package.xml
**What i am doing in this PR?**
- I am fixing the sliders (slider and range-slider) which was trying to assign null values when the maximum values was reached.
- Converting Slider and Range Slider to functional component
**Why?**
Because the library triggers a new value after set the maximum.
I've added 2 singles test cases into the Native Components Test Project with static ranges
=> Fixing sliders

packages/theming/atlas/src/native/ts/app/custom-variables.ts, packages/theming/atlas/src/native/ts/core/variables.ts, packages/theming/atlas/src/native/ts/core/widgets/navigation.ts, packages/theming/atlas/src/native/ts/types/variables.d.ts
Fix: https://github.com/mendix/Atlas-UI-Framework/issues/74
=> feat(atlas-ui): add progressOverlay vars

package-lock.json, packages/tools/pluggable-widgets-tools/package.json
- Upgrade Mendix dependency
- Bump minor version
=> pluggable-widgets-tools: prepare for 8.15 release

packages/pluggableWidgets/app-events-native/package.json, packages/pluggableWidgets/app-events-native/src/AppEvents.tsx, packages/pluggableWidgets/app-events-native/src/AppEvents.xml, packages/pluggableWidgets/app-events-native/src/package.xml, packages/pluggableWidgets/app-events-native/typings/AppEventsProps.d.ts
Add an unload event to the app-events-native widget, triggered in componentWillUnmount
=> feat(app-events-native): add unload event

packages/tools/generator-widget/README.md, packages/tools/pluggable-widgets-tools/README.md
- Add node version requirement
- Restructure and rewrite some parts of generator README.md
=> Improve generator-widget and pluggable-widgets-tools documentation

.github/workflows/PublishNpm.yml, .github/workflows/ScriptTests.yml, .github/workflows/UnitTests.yml, .github/workflows/WebAutomatedTests.yml
**Why?**
Because variables are not shared between steps, they are independent processes, so to fix it I am using the output of the steps.
**What else?**
Github actions does not checkout master branch, so lerna cannot compare to it and do partial build, so I added a `git fetch` for the targeted branch
=> Fix GH Partial Builds

packages/theming/atlas/src/native/ts/app/custom-variables.ts
Fix dark mode detection in RN 0.63 (MX9)
=> fix(atlas): fixing dark mode detection

packages/theming/atlas/src/web/sass/core/widgets/_layoutgrid.scss
https://mendix.atlassian.net/browse/WT-2807
=> [WT-2807] - Add old bootstrap classnames

README.md, packages/jsActions/native-mobile-resources/src/camera/TakePicture.ts, packages/jsActions/native-mobile-resources/src/camera/TakePictureAdvanced.ts
Fixes ticket #110264 from @mgroeneweg
=> feat(native-mobile-resources): making take picture action available in dutch

package-lock.json, packages/jsActions/nanoflow-commons/package.json, packages/jsActions/native-mobile-resources/package.json, packages/pluggableWidgets/app-events-native/package.json, packages/pluggableWidgets/intro-screen-native/package.json, packages/pluggableWidgets/web-view-native/package.json, packages/pluggableWidgets/web-view-native/src/__tests__/__snapshots__/WebView.spec.tsx.snap, packages/pluggableWidgets/web-view-native/src/package.xml
- Aligning react-native-libraries with AppDev
=> [WT-1990] Updating react native libs

packages/pluggableWidgets/datagrid-date-filter-web/src/components/DatePicker.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/FilterSelector.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/__tests__/FilterComponent.spec.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/__tests__/__snapshots__/FilterComponent.spec.tsx.snap, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/ui/DatagridDropdownFilter.scss, packages/pluggableWidgets/datagrid-number-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/components/FilterSelector.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/components/FilterSelector.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Header.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/ui/Datagrid.scss, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/pluggableWidgets/datagrid-web/typings/react-table-config.d.ts
- Fixing filtering of data when no data or invalid data was in the column
- Fixing preview of DG widget in design mode (make consistency using `{attribute}`)
- Fixing drop-down filter placeholder color
- Fixing click ouside actions on filters to avoi glitch when re-clicking on the filter type button and date picker
- Fixing wrong first row top border in DG
- Fixing clickable item area for drop-down filter (when multiselect is enabled)
- Fixing space of header icons when alignment is set to right
- Implementing onclick action in rows for DG
- Fixing empty placeholder (It was showing even with `no` selected in the properties)
=> Data grid - Improvements

.gitmodules, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/tests/e2e/objects/datagrid.widget.ts, packages/pluggableWidgets/datagrid-web/tests/e2e/specs/DataGrid.spec.ts, packages/pluggableWidgets/datagrid-web/tests/e2e/tsconfig.json, packages/tools/pluggable-widgets-tools/configs/eslint.js.base.json, packages/tools/pluggable-widgets-tools/configs/eslint.ts.base.json, packages/tools/pluggable-widgets-tools/test-config/wdio.conf.js
**Why?**
Adding e2e tests to cover datagrid-web widget.
=> test(datagrid-web): add e2e test

packages/pluggableWidgets/bar-chart-native/README.md
=> Native bar chart: add documentation

.gitmodules, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/tests/e2e/objects/datagrid.widget.ts, packages/pluggableWidgets/datagrid-text-filter-web/tests/e2e/specs/DataGridTextFilter.spec.ts, packages/pluggableWidgets/datagrid-text-filter-web/tests/e2e/tsconfig.json, scripts/test/updateAtlas.js
**Why?**
Adding e2e tests to cover datagrid-text-filter-web widget.
=> test(datagrid-text-filter-web): add e2e test

packages/theming/atlas/content/index-rtl.html, packages/theming/atlas/content/index.html, packages/theming/atlas/content/login-with-sso.html, packages/theming/atlas/content/login.html, packages/theming/atlas/content/manifest-overrides.webmanifest, packages/theming/atlas/src/native/ts/core/widgets/navigation.ts
This PR ports some missing changes by UI Core that were present in Atlas 2, as discussed with @mmehmetAliIzci.
=> Port Atlas changes

packages/pluggableWidgets/datagrid-web/src/components/Pagination.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Pagination.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
In this PR i am fixing the pagination when there is no items to be paginated.
=> [WT-3152] Fix DataGrid pagination without items

packages/pluggableWidgets/video-player-web/src/components/SizeContainer.tsx, packages/tools/pluggable-widgets-tools/jest.config.js, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/index.spec.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/containment.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/file.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/containment.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/datasource.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/file.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/icon.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/index.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-action.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-files.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-image.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/generate.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/generateClientTypes.ts, packages/tools/pluggable-widgets-tools/src/typings-generator/helpers.ts, packages/tools/pluggable-widgets-tools/tests/commands.js
- Add id prop for web widgets with system property Label
- Bonus fix: properly declare tabIndex prop as optional
=> [WT-3097] PIW tools - Generator doesn't include id property in typings (Mx 8)

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
**What I am doing in this PR?**
I am just renaming properties and changing the way objects are being shown in the columns list
**Why?**
To make it better for users
No specific details.
=> [WC-117] Data grid - Organize properties

packages/theming/atlas/src/themesource/atlas_ui_resources/native/core/helpers/images.ts, packages/theming/atlas/src/themesource/atlas_ui_resources/native/core/widgets/popupmenu.ts, packages/theming/atlas/src/themesource/atlas_ui_resources/native/design-properties.json
New design properties for image is implemented and added:
- size
- shape
More usability and compliance with designs
- Fix darkmode background for popupmenu
=> [NC-45] Add new design properties for image

packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/tests/e2e/specs/DataGridTextFilter.spec.ts, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/tests/e2e/specs/DataGrid.spec.ts, scripts/test/updateAtlas.js
Description
It's necessary to verify if the context is the same when you apply a filter and try to view the data using a pop-up page.
=> [WC-138] Data grid - Create e2e to verify the context when filtering

packages/theming/atlas/src/themesource/atlas_ui_resources/web/core/helpers/_tables.scss, packages/theming/atlas/src/themesource/atlas_ui_resources/web/design-properties.json
- Creating missing design properties for Table
- Removing unused classes for Table
=> [WC-73] Atlas: adding design properties for Table and removing classes

packages/pluggableWidgets/qr-code-native/package.json, packages/pluggableWidgets/qr-code-native/src/package.xml
- After adding preview, we need to bump major since it is a breaking change
=> fix(qr-code-native): bump major

packages/pluggableWidgets/animation-native/package.json, packages/pluggableWidgets/animation-native/src/package.xml, packages/pluggableWidgets/listview-swipe-native/src/package.xml, packages/pluggableWidgets/rating-native/package.json, packages/pluggableWidgets/rating-native/src/package.xml
Align version bump for all previews to major update
=> Bump versions of native widgets

package-lock.json, packages/tools/pluggable-widgets-tools/configs/eslint.js.base.json, packages/tools/pluggable-widgets-tools/configs/eslint.ts.base.json, packages/tools/pluggable-widgets-tools/package.json
In this PR I am including ESLint rules for hooks
=> PIW-Tools: implementing eslint rules for hooks

.github/workflows/ScriptTests.yml, .github/workflows/UnitTests.yml, .github/workflows/WebAutomatedTests.yml
**What?**
- This changes the way we check for changed files. Now only added and modified will be compared.
=> [GH Action] Forcing to use only added and modified files

packages/pluggableWidgets/fieldset-web/tests/e2e/specs/Fieldset.spec.ts
What?
I am removing all the unnecessary Atlas resources from our test projects. So, we won't have any else issue related to widget dependency when we running our e2e tests.
=> test: strip out atlas resources

packages/theming/atlas/src/theme/native/custom-variables.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/widgets/tabcontainer.ts, packages/theming/atlas/src/themesource/atlas_core/native/variables.ts
Fix darkmode and spacing issue for tabcontainer
No ss change needed
=> [NC-60] fix(atlas-ui): fix tabcontainer darkmode / spacing

packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_simplemenubar.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/widgets/_header.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/widgets/_simplemenubar.scss, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas-phone.scss, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas-responsive.scss, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas-tablet.scss, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas.scss
PWA layouts added to atlas design system for tablet and mobile.
=> PWA layouts

packages/theming/atlas/src/theme/native/custom-variables.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/widgets/tabcontainer.ts, packages/theming/atlas/src/themesource/atlas_core/native/types/variables.d.ts, packages/theming/atlas/src/themesource/atlas_core/native/variables.ts
Fix forgotten border radius and text color
=> fix(atlas-ui): fix tabcontainer border radius

packages/pluggableWidgets/progress-bar-web/package.json, packages/pluggableWidgets/progress-bar-web/tests/e2e/specs/errors.spec.ts, packages/pluggableWidgets/progress-bar-web/tests/e2e/specs/onClick.spec.ts
**What?**
Update the progress-bar test project and all the test specs to the new one. Remove old custom widget tests.
=> Update progress bar e2e project and specs

packages/pluggableWidgets/badge-button-web/package.json, packages/pluggableWidgets/badge-web/package.json, packages/pluggableWidgets/fieldset-web/package.json, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/progress-bar-web/package.json
Ensure the script cmds using `cross-env` work when run from local package.json and root package.json (via lerna).
=> Use linked cross-env dependency

packages/theming/atlas/src/themesource/atlas_web_content/web/main.scss, packages/theming/atlas/src/themesource/atlas_web_content/web/pagetemplates/_statuspage.scss
More of https://github.com/mendix/widgets-resources/pull/506
=> feat(atlas-ui): add styling for confirmation status page page template

packages/pluggableWidgets/progress-circle-web/package.json, packages/pluggableWidgets/progress-circle-web/tests/e2e/specs/ProgressCircle.spec.ts, packages/pluggableWidgets/progress-circle-web/tests/e2e/tsconfig.json
What?
Update the progress-circle test project and all the test specs to the new one. Remove old custom widget tests.
=>  Update progress circle e2e project and specs

packages/theming/atlas/src/theme/web/custom-variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_navigation-bar.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_navigation-tree.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_simple-menu-bar.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/widgets/_navigation-tree.scss, packages/theming/atlas/src/themesource/atlas_core/web/design-properties.json, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas-responsive.scss, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas.scss
Atlas Topbar to reflect the new MxDoc
=> Atlas topBar and sidebar

packages/pluggableWidgets/bar-chart-native/package.json, packages/pluggableWidgets/bar-chart-native/src/BarChart.editorConfig.ts, packages/pluggableWidgets/line-chart-native/package.json, packages/pluggableWidgets/line-chart-native/src/LineChart.editorConfig.ts, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.editorConfig.ts, packages/theming/atlas/src/theme/native/custom-variables.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/helpers/helperclasses.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/helpers/introscreen.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/widgets/checkbox.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/widgets/feedback.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/widgets/popupmenu.ts, packages/theming/atlas/src/themesource/atlas_core/native/core/widgets/togglebuttons.ts, packages/theming/atlas/src/themesource/atlas_core/native/design-properties.json, packages/theming/atlas/src/themesource/atlas_core/native/types/variables.d.ts, packages/theming/atlas/src/themesource/atlas_core/native/variables.ts, packages/theming/atlas/src/themesource/atlas_core/web/design-properties.json, packages/theming/atlas/src/themesource/atlas_nativemobile_content/native/buildingblocks/splitview.ts
=> Fix native / web consistency checks compatible with Mendix 9

packages/theming/atlas/src/theme/web/custom-variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/base/_login.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_navigation-bar.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_navigation-tree.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_simple-menu-bar.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/widgets/_input.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/widgets/_navigation-bar.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/widgets/_navigation-tree.scss, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas-responsive.scss, packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas.scss, packages/theming/atlas/src/themesource/atlas_web_content/web/buildingblocks/_alert.scss
- Aligning monorepo with latest @cjfhodges changes in the reference app around topbar and validation
=> fix(atlas-ui): align styles from reference app

packages/customWidgets/calendar-web/tests/e2e/objects/calendar.widget.ts, packages/customWidgets/calendar-web/tests/e2e/specs/renderDifferentViews.spec.ts
**What?**
Add a new e2e test  to cover this case: https://github.com/mendix/widgets-resources/pull/555
=> Calendar-web -  Create new e2e test to verify start date attribute over association

packages/pluggableWidgets/accessibility-helper-web/package.json
**What?**
Enable e2e test again.
=> A11y-helper enable e2e test again

packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_list-view.scss, packages/theming/atlas/src/themesource/atlas_web_content/web/pagetemplates/_statuspage.scss
- Contains Atlas changes ✅ 
Customer feedback on Atlas Core and Atlas Web Content
Fix to Atlas_Core where when using listview-col implementation, we weren't wrapping listitems
Fix to Atlas_Web_Content for a class typo. .statuspage-subtite -> .statuspage-subtitle
Fix to Atlas_Core where when using listview-col implementation, we weren't wrapping listitems
Fix to Atlas_Web_Content for a class typo. .statuspage-subtite -> .statuspage-subtitle
_..._
=> Atlas feedback core and web content

packages/customWidgets/image-viewer-web/tests/e2e/specs/errors.spec.ts
=> test(image-viewer-web): fix e2e test

packages/pluggableWidgets/switch-web/CHANGELOG.md
=> [W] Release Switch 3.0.0

packages/pluggableWidgets/rating-web/src/StarRating.editorConfig.ts, packages/pluggableWidgets/rating-web/src/StarRating.editorPreview.tsx, packages/pluggableWidgets/rating-web/src/StarRating.tsx, packages/pluggableWidgets/rating-web/src/StarRating.xml, packages/pluggableWidgets/rating-web/src/components/__tests__/StarRating.spec.tsx, packages/pluggableWidgets/rating-web/typings/StarRatingProps.d.ts
- Contains breaking changes ✅
This PR minimizes the impact while migrating from v1 to v2 as by mistake i renamed the properties.
-
Not needed
=> fix(rating-web): minimizing conversion conflicts

.github/workflows/PublishNpm.yml
Fix NPM publish workflow.
- Convert double quoted tag matching strings to single quoted ones.
Nothing.
=> Fix NPM publish workflow

packages/pluggableWidgets/rating-web/CHANGELOG.md
=> Adding changelog to rating-web

packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.editorPreview.tsx, packages/pluggableWidgets/barcode-scanner-web/src/assets/previewQrCode.svg, packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx, packages/pluggableWidgets/barcode-scanner-web/src/components/__tests__/BarcodeScanner.spec.tsx, packages/pluggableWidgets/barcode-scanner-web/src/components/__tests__/__snapshots__/BarcodeScanner.spec.tsx.snap, packages/pluggableWidgets/barcode-scanner-web/src/ui/BarcodeScannerPreview.scss
Design preview for barcode scanner widget
=> [WC-437] Add design preview for barcode widget

packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx
Avoid property rerender using memoization
--
Rendering
=> [WC-551] feat(datagrid-web): optimizing property

packages/pluggableWidgets/image-viewer-web/src/ImageViewer.xml, packages/pluggableWidgets/image-viewer-web/typings/ImageViewerProps.d.ts
Move dimensions group to tab for Studio
_Please add a high level explanation of what was changed and how the initial problem was solved_
_..._
=> [WC-553] move dimensions properties group to tab

packages/pluggableWidgets/image-viewer-web/src/ImageViewer.tsx, packages/pluggableWidgets/image-viewer-web/src/ImageViewer.xml, packages/pluggableWidgets/image-viewer-web/src/components/ImageViewer/index.tsx, packages/pluggableWidgets/image-viewer-web/src/components/ImageViewer/ui.tsx, packages/pluggableWidgets/image-viewer-web/src/components/__tests__/ImageViewer.spec.tsx, packages/pluggableWidgets/image-viewer-web/typings/ImageViewerProps.d.ts
- Comply with designs ✅ ❌
Add accessibility and common properties in image viewer
That the accessibility features are working properly
=> [WC-524] Add accessibility and common properties to image viewer

packages/pluggableWidgets/image-viewer-web/src/ImageViewer.editorConfig.ts, packages/pluggableWidgets/image-viewer-web/src/ImageViewer.tsx, packages/pluggableWidgets/image-viewer-web/src/ImageViewer.xml, packages/pluggableWidgets/image-viewer-web/src/components/ImageViewer/index.tsx, packages/pluggableWidgets/image-viewer-web/src/components/__tests__/ImageViewer.spec.tsx, packages/pluggableWidgets/image-viewer-web/typings/ImageViewerProps.d.ts
- Subset of consistency checks
- Hide width and height properties when the respective enum value is "auto"
- url -> link, rephrase
- add displayAs widget property, for either thumbnail or fullImage.
=> [WC-562] Process image viewer web citizen dev feedback

packages/pluggableWidgets/accordion-web/CHANGELOG.md
This PR prepares the release notes for the accordion web widget v1.0.0
- Update changelog.
x
=> [WC-407] Accordion web - Prepare release notes

packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/CHANGELOG.md
For Maps, Datagrid, and Barcode Scanner
=> Update outdated CHANGELOG.md files

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/package.json
Prepare for release of video player web.
=> [WC-576] Video player (web) - prepare for v1.1.0 release

packages/pluggableWidgets/video-player-web/src/package.xml
Align version in XML of video player web.
=> Video player (web) - Align version in XML

packages/pluggableWidgets/image-viewer-web/src/ImageViewer.xml
Based on feedback by @diego-antonelli
Nothing really to test here.
=> feat(image-viewer-web): put an . at the end of descriptions

packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml
Add support for Boolean attributes in the Data grid drop-down filter
--
--
=> [WC-634] Data Grid - adding support for boolean in dropdown filter

packages/pluggableWidgets/progress-bar-web/CHANGELOG.md, packages/pluggableWidgets/progress-circle-web/CHANGELOG.md
=> Add progress bar and circle changelogs

.gitmodules, packages/tools/pluggable-widgets-tools/CHANGELOG.md, packages/tools/pluggable-widgets-tools/package.json, packages/tools/pluggable-widgets-tools/scripts/e2e.js, packages/tools/pluggable-widgets-tools/scripts/m2ee.yml, packages/tools/pluggable-widgets-tools/scripts/mxbuild.Dockerfile, packages/tools/pluggable-widgets-tools/scripts/runtime.Dockerfile, packages/tools/pluggable-widgets-tools/scripts/runtime.sh
- Contains breaking changes ✅
- Compatible with: MX 8️⃣
Backporting current e2e scripts and retrieval of Mendix version from master.
Changed only e2e scripts.
-
=> feat(pluggable-widgets-tools): backporting fix for latest mendix version in e2e scripts

packages/pluggableWidgets/maps-web/CHANGELOG.md
=> Maps (web) - Update changelog

packages/pluggableWidgets/maps-web/src/package.xml
=> Maps (web) - Fix inconsistent version xml

packages/theming/atlas/src/themesource/atlas_core/web/layouts/_layout-atlas.scss
- Contains breaking changes ✅
- Contains Atlas changes ✅
Removing box-shadow from sidebar
_Please add a high level explanation of what was changed and how the initial problem was solved_
--
=> fix(atlas-ui): remove box-shadow

packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml
Fixed default values.
-
Should be tested the default values and also the view state for this filter.
=> [WC-656] Data grid drop-down filter: fixing default value

packages/pluggableWidgets/scroll-container-web/CHANGELOG.md, packages/pluggableWidgets/scroll-container-web/README.md, packages/pluggableWidgets/scroll-container-web/package.json, packages/pluggableWidgets/scroll-container-web/src/ScrollContainer.editorConfig.ts, packages/pluggableWidgets/scroll-container-web/src/ScrollContainer.editorPreview.tsx, packages/pluggableWidgets/scroll-container-web/src/ScrollContainer.tsx, packages/pluggableWidgets/scroll-container-web/src/ScrollContainer.xml, packages/pluggableWidgets/scroll-container-web/src/components/ScrollContainer.tsx, packages/pluggableWidgets/scroll-container-web/src/components/__tests__/ScrollContainer.spec.tsx, packages/pluggableWidgets/scroll-container-web/src/components/__tests__/__snapshots__/ScrollContainer.spec.tsx.snap, packages/pluggableWidgets/scroll-container-web/src/package.xml, packages/pluggableWidgets/scroll-container-web/src/ui/scroll-container.scss, packages/pluggableWidgets/scroll-container-web/tsconfig.json, packages/pluggableWidgets/scroll-container-web/typings/ScrollContainerProps.d.ts
Pluggable version of a scroll container that allows users to embed it in layouts and make content scrollable if a parent contain height.
-
-
=> Introduce Scroll Container

packages/pluggableWidgets/accordion-web/CHANGELOG.md, packages/pluggableWidgets/accordion-web/package.json, packages/pluggableWidgets/accordion-web/src/Accordion.editorConfig.ts, packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx, packages/pluggableWidgets/accordion-web/src/Accordion.xml, packages/pluggableWidgets/accordion-web/src/package.xml
Prepare accordion (web) for release v1.1.0
- Update changelog.
- Bump minor version.
- Improve widget property & placeholder descriptions.
x
=> [WC-661 ] Accordion (web) - Prepare for release v1.1.0

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/README.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.editorConfig.ts, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.xml, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/Gallery.spec.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/__snapshots__/Gallery.spec.tsx.snap, packages/pluggableWidgets/gallery-web/src/package.xml, packages/pluggableWidgets/gallery-web/src/ui/gallery-main.scss, packages/pluggableWidgets/gallery-web/tsconfig.json, packages/pluggableWidgets/gallery-web/typings/GalleryProps.d.ts
Introduce the new flexible gid candidate to replace ListView + ListView Controls and Grid/Template Grid.
Everything is shiny.
Basic coverage for first interactions.
e2e tests not implemented yet.
=> [WC-602] Gallery widget

packages/pluggableWidgets/accessibility-helper-web/CHANGELOG.md, packages/pluggableWidgets/accessibility-helper-web/package.json, packages/pluggableWidgets/accessibility-helper-web/src/AccessibilityHelper.editorConfig.ts, packages/pluggableWidgets/accessibility-helper-web/src/package.xml
- Comply with designs ✅ ❌ (pending approval)
- Comply with PM's requirements ✅ ❌ (pending approval)
Add structure preview for accessibility helper
=> [WC-288]: add structure preview for a11y helper

packages/pluggableWidgets/fieldset-web/CHANGELOG.md, packages/pluggableWidgets/fieldset-web/package.json, packages/pluggableWidgets/fieldset-web/src/Fieldset.editorConfig.ts, packages/pluggableWidgets/fieldset-web/src/package.xml
- Comply with designs ✅❌  (Waiting for PM approval)
Add structure preview
=> [WC-354]: add structure preview for fieldset

packages/pluggableWidgets/maps-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/maps-web/src/Maps.xml, packages/pluggableWidgets/maps-web/src/package.xml
Renaming Markers and Marker list to Static and Dynamic markers
Only renamed properties in the xml.
Smoke tests
=> feat(maps-web): renaming properties

packages/pluggableWidgets/image-viewer-web/src/ImageViewer.editorConfig.ts, packages/pluggableWidgets/image-viewer-web/src/ImageViewer.editorPreview.tsx, packages/pluggableWidgets/image-viewer-web/src/ImageViewer.tsx, packages/pluggableWidgets/image-viewer-web/src/ImageViewer.xml, packages/pluggableWidgets/image-viewer-web/typings/ImageViewerProps.d.ts
- Contains unit tests ✅ ❌
- Contains breaking changes ✅ ❌
- Contains Atlas changes ✅ ❌
- Rename widget properties
- Update typings from previous order change
- fix dynamic imageurl detector so design preview always shows placeholder if there's a dynamic url
- for dynamic images, add a default image placeholder and account for it in studio and the widget
- "Image link" -> "Image URL"
=> [WC-672] Process Image viewer web studio pro feedback

packages/customWidgets/rich-text-web/CHANGELOG.md, packages/customWidgets/rich-text-web/package.json, packages/customWidgets/rich-text-web/src/package.xml
Adding changelog and bumping version for #835 
--
--
=> feat(rich-text-web): adding changelog and bump version

packages/pluggableWidgets/tree-view-web/src/components/TreeView.tsx, packages/pluggableWidgets/tree-view-web/src/components/TreeViewBranchContext.ts, packages/pluggableWidgets/tree-view-web/src/ui/TreeView.scss, packages/theming/atlas/src/theme/web/exclusion-variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/_exclusion-variables.scss, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_tree-node.scss, packages/theming/atlas/src/themesource/atlas_core/web/design-properties.json, packages/theming/atlas/src/themesource/atlas_core/web/main.scss
- Contains Atlas changes ✅ 
- Adding design properties
Three design properties:
- hover
- striped
- bordered
- This should not be merged until released
=> [WC-592]: implement tree node design properties

packages/pluggableWidgets/gallery-web/src/Gallery.editorConfig.ts, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/__snapshots__/Gallery.spec.tsx.snap
Improving readability of gallery through Screen Readers.
- Added correct roles for items and the list itself.
Screen reader announcing items.
=> [WC-732] Improving Gallery accessibility

packages/pluggableWidgets/tree-view-web/src/TreeView.editorConfig.ts
=> feat(tree-view-web): change empty header caption for structure preview

packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.xml, packages/pluggableWidgets/datagrid-date-filter-web/src/components/DatePicker.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/DatePicker.spec.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/__snapshots__/DatePicker.spec.tsx.snap, packages/pluggableWidgets/datagrid-date-filter-web/typings/DatagridDateFilterProps.d.ts, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.xml, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.xml, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.xml, packages/pluggableWidgets/dropdown-sort-web/src/DropdownSort.editorPreview.tsx, packages/pluggableWidgets/dropdown-sort-web/src/DropdownSort.tsx, packages/pluggableWidgets/dropdown-sort-web/src/DropdownSort.xml, packages/pluggableWidgets/dropdown-sort-web/src/components/SortComponent.tsx, packages/pluggableWidgets/dropdown-sort-web/src/components/__test__/SortComponent.spec.tsx, packages/pluggableWidgets/dropdown-sort-web/src/components/__test__/__snapshots__/SortComponent.spec.tsx.snap, packages/pluggableWidgets/dropdown-sort-web/typings/DropdownSortProps.d.ts
Implement a11y properties for missing fields in filters.
--
A11y in general for Filters and Sort
=> [WC-755] Improve filters accessibility

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/pluggableWidgets/gallery-web/src/Gallery.editorConfig.ts, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.xml, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/Gallery.spec.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/__snapshots__/Gallery.spec.tsx.snap, packages/pluggableWidgets/gallery-web/typings/GalleryProps.d.ts
Adding accessibility aria labels for regions.
Added aria-label for divs containing regions.
General a11y of filter area and empty message.
=> [WC-750] Gallery a11y properties

packages/pluggableWidgets/image-web/src/Image.editorConfig.ts, packages/pluggableWidgets/image-web/src/Image.editorPreview.tsx, packages/pluggableWidgets/image-web/src/Image.tsx, packages/pluggableWidgets/image-web/src/Image.xml, packages/pluggableWidgets/image-web/src/components/Image/index.tsx, packages/pluggableWidgets/image-web/src/components/Image/ui.tsx, packages/pluggableWidgets/image-web/src/components/__tests__/Image.spec.tsx, packages/pluggableWidgets/image-web/src/components/__tests__/__snapshots__/Image.spec.tsx.snap, packages/pluggableWidgets/image-web/src/ui/Image.scss, packages/pluggableWidgets/image-web/tests/e2e/objects/constants.ts, packages/pluggableWidgets/image-web/tests/e2e/objects/imageViewer.widget.ts, packages/pluggableWidgets/image-web/tests/e2e/specs/dataTypes.spec.ts, packages/pluggableWidgets/image-web/tests/e2e/specs/differentViews.spec.ts, packages/pluggableWidgets/image-web/tests/e2e/specs/onClick.spec.ts, packages/pluggableWidgets/image-web/typings/ImageProps.d.ts, packages/theming/atlas/src/themesource/atlas_core/web/core/helpers/_image.scss, packages/theming/atlas/src/themesource/atlas_core/web/design-properties.json
- Comply with designs ✅ ❌ (pending)
- Add background image feature.
- also rename image-viewer to image in code
=> [WC-535] Add background image feature to image widget

packages/pluggableWidgets/image-web/CHANGELOG.md, packages/pluggableWidgets/image-web/package.json
=> feat(image-web): update image marketplaceid and CHANGELOG

packages/modules/data-widgets/package.json
Bump data-widgets module version.
--
--
=> fix(data-widgets): bump version

packages/pluggableWidgets/maps-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/maps-web/src/package.xml
Add version and changes information for Maps widget
Bumping version of the widget, adding CHANGELOG.md information
=> chore(maps-web): bump version, added changelog

packages/pluggableWidgets/maps-web/src/Maps.editorPreview.tsx
Purpose is to add design properties on container div for preview
this is addition to [this PR](https://github.com/mendix/widgets-resources/pull/1077)
If properties work properly
=> [WC-863] added class and styles from appearance on container div

packages/pluggableWidgets/line-chart-web/tests/e2e/specs/LineChart.spec.ts
Fix the first screenshot testing check which it's failing
Added a new timeout in the first checks to wait the page loads correctly.
Automation should work.
=> Fix line-chart screenshot test failing

packages/pluggableWidgets/slider-web/src/Slider.editorConfig.ts, packages/pluggableWidgets/slider-web/src/Slider.editorPreview.tsx, packages/pluggableWidgets/slider-web/src/Slider.tsx, packages/pluggableWidgets/slider-web/src/Slider.xml, packages/pluggableWidgets/slider-web/src/ui/Slider.scss, packages/pluggableWidgets/slider-web/typings/SliderProps.d.ts
=> [WC-879] Studio Slider Feedback

packages/customWidgets/calendar-web/src/components/CalendarContainer.ts
Address these warnings so they don't show in PRs 😮
=> feat(calendar-web): fix linter warnings

packages/modules/data-widgets/package.json
Bump data widgets version
--
--
=> feat(data-widgets): bump version

packages/pluggableWidgets/range-slider-web/src/RangeSlider.editorPreview.tsx, packages/pluggableWidgets/range-slider-web/src/RangeSlider.tsx, packages/pluggableWidgets/range-slider-web/src/ui/RangeSlider.scss, packages/pluggableWidgets/range-slider-web/typings/RangeSliderProps.d.ts
Fixing properties for editorPreview, fixing multiple requires and adding missing disabled state for design mode.
--
General usage
=> fix(range-slider-web): fixing properties

packages/modules/data-widgets/package.json
=> chore(data-widgets): bump version

packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md, packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.xml
Change Mendix SP + Studio category
Removed from Studio blacklist
=> [WC-903] Change barcode scanner category to Images, videos & files

packages/pluggableWidgets/accessibility-helper-web/package.json
Can't execute automation for a11y-helper without these fields.
=> [WC-872] add repository information for automation of accessibility-helper-web

packages/modules/data-widgets/package.json, packages/pluggableWidgets/barcode-scanner-web/package.json, packages/pluggableWidgets/barcode-scanner-web/src/package.xml, packages/pluggableWidgets/timeline-web/package.json, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/package.xml
=> [WC-872] Fix widgets for automation 9.9.1

packages/pluggableWidgets/range-slider-web/CHANGELOG.md, packages/pluggableWidgets/slider-web/CHANGELOG.md
Thought this wasn't necessary but forgot it's considered a major version release of an existing widget instead of entirely new one.
=> [WC-872] Add release notes to sliders for 9.9.1

packages/pluggableWidgets/slider-web/package.json, packages/pluggableWidgets/slider-web/tests/e2e/objects/Slider.widget.ts, packages/pluggableWidgets/slider-web/tests/e2e/specs/Slider.spec.ts, packages/pluggableWidgets/slider-web/tests/e2e/tsconfig.json
Re-enable slider e2e test of slider widget.
- Removed error alerts tests since we're not checking errors on the client-side;
- Removed not used styles test.
=> [WC-888] Re-enable slider e2e test

packages/pluggableWidgets/range-slider-web/package.json, packages/pluggableWidgets/range-slider-web/src/RangeSlider.editorConfig.ts, packages/pluggableWidgets/range-slider-web/src/RangeSlider.xml, packages/pluggableWidgets/range-slider-web/src/package.xml, packages/pluggableWidgets/range-slider-web/typings/RangeSliderProps.d.ts, packages/pluggableWidgets/slider-web/package.json, packages/pluggableWidgets/slider-web/src/Slider.editorConfig.ts, packages/pluggableWidgets/slider-web/src/Slider.xml, packages/pluggableWidgets/slider-web/src/package.xml, packages/pluggableWidgets/slider-web/typings/SliderProps.d.ts
- Compatible with:  9️⃣
Re group widget properties to align Studio and Studio Pro
Just changes in *.xml file
Widget settings dialog/panel
=> [WC-986]: Slider and range slider studiou group feedback 

packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
- Contains unit tests  ❌
- Contains breaking changes  ❌
- Contains Atlas changes  ❌
- Compatible with:  9️⃣
Studio feedback
changes in RichText properties
=> [WC-1010] RichText editor studio feedback

packages/pluggableWidgets/color-picker-web/CHANGELOG.md, packages/pluggableWidgets/color-picker-web/package.json, packages/pluggableWidgets/color-picker-web/src/ColorPicker.editorConfig.ts, packages/pluggableWidgets/color-picker-web/src/ColorPicker.xml, packages/pluggableWidgets/color-picker-web/src/package.xml, packages/pluggableWidgets/color-picker-web/typings/ColorPickerProps.d.ts
We updated structure props names and descriptions, also the ordering for a studio.
One more round of E2E tests, check if color picker renders the exact type and mode which was selected in a configuration.
=> [WC-1011] Color picker changes based on studio feedback

packages/pluggableWidgets/column-chart-web/src/ColumnChart.editorConfig.ts, packages/pluggableWidgets/column-chart-web/src/ColumnChart.tsx, packages/pluggableWidgets/column-chart-web/src/ColumnChart.xml, packages/pluggableWidgets/column-chart-web/src/__tests__/ColumnChart.spec.tsx, packages/pluggableWidgets/column-chart-web/typings/ColumnChartProps.d.ts
- Contains breaking changes ✅
- Compatible with Studio ✅ ❌
- Apply changes requested by PM
=> [WC-1051] Column Chart feedback

.github/workflows/WebAutomatedTests.yml, packages/jsActions/native-mobile-resources/package.json
Add fbjs to dependency list. Our release notes describes how to handle installation of dependencies.
One of our deps, `@react-native-community/cameraroll`, has a silent dependencyy on `fbjs`.
=> [NC-663] Fix NMR for MX8

packages/jsActions/native-mobile-resources/CHANGELOG.md
=> fix(): update changelog

packages/pluggableWidgets/area-chart-web/package.json, packages/pluggableWidgets/area-chart-web/src/package.xml, packages/pluggableWidgets/bar-chart-web/package.json, packages/pluggableWidgets/bar-chart-web/src/package.xml, packages/pluggableWidgets/bubble-chart-web/package.json, packages/pluggableWidgets/bubble-chart-web/src/package.xml, packages/pluggableWidgets/line-chart-web/package.json, packages/pluggableWidgets/line-chart-web/src/package.xml, packages/pluggableWidgets/pie-doughnut-chart-web/package.json, packages/pluggableWidgets/pie-doughnut-chart-web/src/package.xml
=> Update Charts versions

packages/pluggableWidgets/area-chart-web/src/AreaChart.editorConfig.ts, packages/pluggableWidgets/area-chart-web/src/AreaChart.tsx, packages/pluggableWidgets/area-chart-web/src/AreaChart.xml, packages/pluggableWidgets/area-chart-web/src/__tests__/AreaChart.spec.tsx, packages/pluggableWidgets/area-chart-web/typings/AreaChartProps.d.ts, packages/pluggableWidgets/bar-chart-web/src/BarChart.xml, packages/pluggableWidgets/bubble-chart-web/src/BubbleChart.editorConfig.ts, packages/pluggableWidgets/bubble-chart-web/src/BubbleChart.tsx, packages/pluggableWidgets/bubble-chart-web/src/BubbleChart.xml, packages/pluggableWidgets/bubble-chart-web/src/__tests__/BubbleChart.spec.tsx, packages/pluggableWidgets/bubble-chart-web/typings/BubbleChartProps.d.ts, packages/pluggableWidgets/column-chart-web/src/ColumnChart.xml, packages/pluggableWidgets/line-chart-web/src/LineChart.xml, packages/pluggableWidgets/pie-doughnut-chart-web/src/PieChart.xml, packages/shared/charts/src/hooks/usePlotChartDataSeries.ts
Extension on #1350 
- Implement the remainder of the charts (area and bubble) since they were forgotten cuz they werne't mentioned in the original paper doc
- Move visibility to its own section as per requested by Studio
- Extra: there was a wrong import and incorrect typing, so I fixed that
- Same thing as before but for area and bubble
- That Visibility is its own section in Studio now as they have requested (see doc)
=> [WC-1085] Charts Remaining Studio Feedback

packages/tools/pluggable-widgets-tools/configs/rollup.config.js
…WC-1048)
- Contains unit tests ✅ ❌
- Contains breaking changes ✅ ❌
- Contains Atlas changes ✅ ❌
- Contains e2e tests ✅ ❌
- Is accessible ✅ ❌
- Compatible with Studio ✅ ❌
- Cross-browser compatible ✅ ❌
- Works in Android ✅ ❌
- Works in iOS ✅ ❌
- Works in Tablet ✅ ❌
- Comply with designs ✅ ❌
**_Please remove unnecessary emojis and sections and this comment before proceeding_**
_..._
_Please add a high level explanation of what was changed and how the initial problem was solved_
_..._
=> [WC-1048] change PWT config to copy CSS assets instead of inlining them

packages/modules/data-widgets/src/themesource/datawidgets/public/resources/dropdown-arrow.svg, packages/modules/data-widgets/src/themesource/datawidgets/web/datagrid-filters.scss
- Contains unit tests ✅ ❌
- Contains breaking changes ✅ ❌
- Contains Atlas changes ✅ ❌
- Contains e2e tests ✅ ❌
- Is accessible ✅ ❌
- Compatible with Studio ✅ ❌
- Cross-browser compatible ✅ ❌
- Works in Android ✅ ❌
- Works in iOS ✅ ❌
- Works in Tablet ✅ ❌
- Comply with designs ✅ ❌
**_Please remove unnecessary emojis and sections and this comment before proceeding_**
- Fix CSP inline style issue
_Please add a high level explanation of what was changed and how the initial problem was solved_
_..._
=> feat: use svg file instead of inline svg

packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap
- Contains breaking changes  ❌
**_Please remove unnecessary emojis and sections and this comment before proceeding_**
Adding additional CSS class makes it easier to style datagrid.
There is additional CSS class `widget-datagird`.
=> [WC-1072] feat(datagrid-web): add special css class for data grid

packages/pluggableWidgets/area-chart-web/src/AreaChart.editorPreview.tsx, packages/pluggableWidgets/bar-chart-web/src/BarChart.editorPreview.tsx, packages/pluggableWidgets/bar-chart-web/src/assets/BarChart-grouped.dark.svg, packages/pluggableWidgets/bar-chart-web/src/assets/BarChart-grouped.light.svg, packages/pluggableWidgets/bar-chart-web/src/assets/BarChart-stacked.dark.svg, packages/pluggableWidgets/bar-chart-web/src/assets/BarChart-stacked.light.svg, packages/pluggableWidgets/bubble-chart-web/src/BubbleChart.editorPreview.tsx, packages/pluggableWidgets/column-chart-web/src/ColumnChart.editorPreview.tsx, packages/pluggableWidgets/column-chart-web/src/assets/ColumnChart-grouped.dark.svg, packages/pluggableWidgets/column-chart-web/src/assets/ColumnChart-grouped.light.svg, packages/pluggableWidgets/column-chart-web/src/assets/ColumnChart-stacked.dark.svg, packages/pluggableWidgets/column-chart-web/src/assets/ColumnChart-stacked.light.svg, packages/pluggableWidgets/heatmap-chart-web/src/HeatMap.editorPreview.tsx, packages/pluggableWidgets/line-chart-web/src/LineChart.editorPreview.tsx, packages/pluggableWidgets/pie-doughnut-chart-web/src/PieChart.editorPreview.tsx, packages/pluggableWidgets/time-series-chart-web/src/TimeSeries.editorPreview.ts, packages/pluggableWidgets/time-series-chart-web/src/TimeSeries.editorPreview.tsx
=> [WC-1126] Charts design preview

packages/pluggableWidgets/area-chart-web/src/AreaChart.xml, packages/pluggableWidgets/time-series-chart-web/src/TimeSeries.xml
Property re-organization for area chart and timeseries
Refactor of the properties after a review of the charts
Rename for Area Chart the property "Data source" to "Series" to align with other Charts
Moved properties X axis label and Y axis label from Data source to General for Timeseries chart
Check property consistency 
=> [WC-1218] Property feedback

packages/pluggableWidgets/accordion-web/CHANGELOG.md, packages/pluggableWidgets/accordion-web/package.json, packages/pluggableWidgets/accordion-web/src/package.xml, packages/pluggableWidgets/accordion-web/src/ui/accordion-main.scss
To fix animation issue related to rotating accordion icons when animation is off.
Moved the animation styles to a container where it suppose to be.
If all the states work correctly
=> [WC-1220] fix rotation issue on not animated items

packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml
=> chore(): update filters changelog

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml
=> chore(): update changelog and bump module version

packages/pluggableWidgets/color-picker-web/cypress/integration/ColorPicker.spec.js
-   PR title properly formatted (`[XX-000]: description`)?  ❌
-   Contains e2e tests ✅ 
-   Cross-browser compatible ✅ 
-   [ ] Bug fix
Create a specific test to run on Firefox for the color-picker-web widget.
Added a copy of one test to run on Firefox only.
=> Color-picker-web specific test for Firefox

packages/pluggableWidgets/language-selector-web/CHANGELOG.md
-   [ ] Bug fix
-   [x] Refactor
Added changelog message which is required for release
=> [WC-1288]: add changelog message for language selector

packages/pluggableWidgets/language-selector-web/CHANGELOG.md, packages/pluggableWidgets/language-selector-web/src/LanguageSelector.xml, packages/pluggableWidgets/language-selector-web/src/package.xml
-   [x] Bug fix
changed id of the widget, made it lowercase to be compliant with other widgets and apps
=> [WC-1320]: Language Selector id and path issues
